- src/dawn/SIR/ASTStmt.cpp
When the ifstmts do not have else, the old equals segfaults
> Bugfix in if Comparison

- cmake/modules/DawnAddCustomDummyTarget.cmake
- docs/basics.rst
Some files, like the integration tests .cpp of gtclang are not included in Qt projects since they are not part of any cmake target. 
This creates functionality to add cpp files in a custom target (that does nothing) with the sole purpose that qt creator can add them to the project
This goes together with Meteoswiss-APN/gtclang#13
> Qt project

- cmake/Addclang-format.cmake
- cmake/modules/Findclang-format.cmake
This PR makes the `find_package` module of clang-format more robust by allowing to search for specific versions. In addition, we fix the version of clang-format to 3.8 when using it.
> Fix clang format

- README.md
- src/dawn/Compiler/DawnCompiler.cpp
- src/dawn/Compiler/Options.inc
- src/dawn/Optimizer/CMakeLists.txt
- src/dawn/Optimizer/MultiStage.cpp
- src/dawn/Optimizer/MultiStage.h
- src/dawn/Optimizer/OptimizerContext.h
- src/dawn/Optimizer/PassDataLocalityMetric.cpp
- src/dawn/Optimizer/PassDataLocalityMetric.h
- src/dawn/Optimizer/PassSetNonTempCaches.cpp
- src/dawn/Optimizer/PassSetNonTempCaches.h
- src/dawn/Optimizer/Stencil.cpp
- src/dawn/SIR/SIR.cpp
- src/dawn/SIR/SIR.h
Addition of PassSetNonTempCaches that decides, which non-temporary variables we should write to a scarchpad based on the metric implemented in  PassDataLocalityMetric . It adds filler / flush stages if need be at the beginning and the end of any given multistage the pass is run on. 
In order to run with this pass enabled, the flag `-fcache-non-temp-fields` can be set.
Small adaptation to the PassDataLocalityMetric to support the updated needs.
> Issue #28, Caching of Non-Temporaries in the IJ-Plane

- src/dawn/SIR/SIRSerializer.cpp
Technical description
====================
`gtclang -write-sir` 
crashes for the example in 
https://github.com/MeteoSwiss-APN/gtclang/blob/master/test/integration-test/CodeGen/globals.cpp
This is a fix.
> fix sir serialization of globals

- src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
- src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.h
Technical Description
==================
considering that the naive backend is for debugging, 
here we automatically add `.sync()` calls to all argument storages before and after each call to a run. 
This largely simplifies all the benchmarking files we have in order project, since explicit sync is not needed anymore
> Sync cxxnaive storages

- src/dawn/Optimizer/AccessComputation.cpp
- src/dawn/Optimizer/PassTemporaryToStencilFunction.cpp
- src/dawn/Optimizer/StatementMapper.cpp
- src/dawn/Optimizer/StencilFunctionInstantiation.cpp
- src/dawn/Optimizer/StencilInstantiation.cpp
- src/dawn/Optimizer/StencilInstantiation.h
This is a fix of the temporary to stencil function pass for the following case, that was caused due to versioning of the fields 
```
#include "gridtools/clang_dsl.hpp"
stencil Test04 {
storage a;
storage b, c, d;
var tmp_a, tmp_b;
void Do() {
tmp_a = a[i + 1] + b;
tmp_b = c[j - 1] + d;
c = tmp_a[i - 1] + b;
d = tmp_b[j + 1] + a;
}
}
};
```
> fix tmptostencil function with fields are versioned

- src/dawn/Compiler/DawnCompiler.cpp
- src/dawn/Compiler/Options.inc
- src/dawn/Optimizer/Pass.h
- src/dawn/Optimizer/PassComputeStageExtents.cpp
- src/dawn/Optimizer/PassFieldVersioning.cpp
- src/dawn/Optimizer/PassInlining.cpp
- src/dawn/Optimizer/PassMultiStageSplitter.cpp
- src/dawn/Optimizer/PassMultiStageSplitter.h
- src/dawn/Optimizer/PassSetStageName.cpp
- src/dawn/Optimizer/PassStageSplitter.cpp
- src/dawn/Optimizer/PassStageSplitter.h
- src/dawn/Optimizer/PassTemporaryFirstAccess.cpp
- src/dawn/Optimizer/PassTemporaryType.cpp
Since our current syntax allows for iterative stencils in the form of 
```
vertical_region(k_start+1, k_end){
var a = computation();
var b = a[k-1] * computation();
a = a / b;
}
```
we are not able to split every statement into a separate multistage since in the second iteration of the k-loop at line two we rely on the third line of this loop to be executed on the first k-level.
Therefore the suggested debugging backend is not a valid option. We moved the splitting of each statement to the stage-level. This relies on the multistage-splitter to be a mandatory, working piece to generate legal code. The option of having a separate algorithm that checks how many cuts we can maximally do in a given multistage without making the code illegal is though after but not yet finalized
> remove debug MSS split and add debug Stage Split

- src/dawn/SIR/SIR.h
- src/dawn/SIR/SIR.proto
- src/dawn/SIR/SIRSerializer.cpp
- test/unit-test/dawn/SIR/TestSIRSerializer.cpp
(this goes with a PR in [GTClang](https://github.com/MeteoSwiss-APN/gtclang/pull/69))
This allows the user to specify the dimensionality of fields that are passed as input. Allowed inputs are:
```
storage
storage_i
storage_j
storage_k
storage_ij
storage_ik
storage_jk
storage_ijk
```
where the first and the last are the same
With this feature we gain two things:
* More error-checks are possible.
Currently you can pass a `storage_j_t` to the stencil and call it with i and k offsets. This can be prevented now if the user specifies the dimensionality of storages used.
* In the near future, there will be a Gridtools update that prohibits the notype-stencils that we currenly use.
In order for our setup to work, we need type information at the time of code-generation.
> Addition of Field-Dimensions

- src/dawn/Support/SourceLocation.cpp
Tiny bug fix in source location comparison tool. 
Should not affect neither performance, test results, etc.
> Source location comparison fix

- src/dawn/IIR/Extents.cpp
- test/unit-test/dawn/IIR/TestExtent.cpp
This is the typical problem, that when we compute the extents of accesses, and it is computed from an offset [k+2], the resulting extent is Extent{0,2}, instead of Extent[2,2]
> fix vertical extents

- src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- src/dawn/CodeGen/Cuda/CudaCodeGen.h
- src/dawn/Optimizer/PassSetSyncStage.cpp
Fix that adds a synchronization after the last stage, if caches are used after the last stage that was synchronized. This is to avoid overwrite buffer of IJ Caches at the next K iteration
> Fix cuda backend

- src/dawn/Optimizer/PassInlining.cpp
- src/dawn/SIR/ASTExpr.h
When expr's of a function are inlined in parent scope, the name of the expr should be changed to the caller expr name
Goes together with https://github.com/MeteoSwiss-APN/gtclang/pull/103
> fix inlining

- src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
- src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- src/dawn/CodeGen/GridTools/GTCodeGen.cpp
Since we're now namespacing the generated code, this method of removing trailing semicolons does no longer work
> removal of the semicolons where needed

- src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
- src/dawn/CodeGen/CodeGen.cpp
- src/dawn/CodeGen/CodeGen.h
- src/dawn/CodeGen/Cuda/CodeGeneratorHelper.cpp
- src/dawn/CodeGen/Cuda/CodeGeneratorHelper.h
- src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- src/dawn/CodeGen/Cuda/CudaCodeGen.h
- src/dawn/CodeGen/Cuda/MSCodeGen.cpp
- src/dawn/CodeGen/GridTools/GTCodeGen.cpp
- src/dawn/CodeGen/GridTools/GTCodeGen.h
we want the code-generation to be reporducible and therefore need the iterators to be over sorted containers. For this to happen we sort the unordered containers used in the compiler to ordered ones in the code-generation where sorting is based on field-id's.
> Codegen sort

- bundle/CMakeLists.txt
- src/dawn-c/CMakeLists.txt
- src/dawn/CMakeLists.txt
- src/dawn/Compiler/CMakeLists.txt
- src/dawn/IIR/CMakeLists.txt
- src/dawn/Optimizer/CMakeLists.txt
- src/dawn/SIR/CMakeLists.txt
- src/dawn/Serialization/CMakeLists.txt
- src/dawn/Support/CMakeLists.txt
- test/unit-test/CMakeLists.txt
The dependencies with proto files didnt work in my system with a newer cmake. 
It seems to be related to the propagation with the dependencies on objects targets. 
Here I moved the affected libraries to static libraries rather than objects
> Fix dependencies

- src/dawn/Compiler/DawnCompiler.cpp
This disables the currently broken temporary-first-access pass that is here for safety but not required to generate correct results. Disabeling it eliminates the false positive error messages
The issue that correct code gets rejected
https://github.com/MeteoSwiss-APN/dawn/issues/163
This PR has no dependencies
> disable currently broken pass Temporary first access

- src/dawn/CodeGen/GridTools/GTCodeGen.cpp
Removing gridtools code generation's unnecessary asserts: multiple identical checks for the same storage types and trivial "positive number > 0" or "negative number < 0" checks. 
#197 
The following was generated before the fix (trivial because the left-hand side of the comparison is always negative):
`static_assert(((-1) * static_cast<int>(storage_ijk_t::storage_info_t::halo_t::template at<0>()) <= 0) ||
(storage_ijk_t::storage_info_t::layout_t::template at<0>() == -1),
"Used extents exceed halo limits.");`
Repeated asserts were also generated when multiple storage fields of the same type (`storage_ijk a,b;`) are present:
`static_assert((static_cast<int>(storage_ijk_t::storage_info_t::halo_t::template at<0>()) >= 2) ||
(storage_ijk_t::storage_info_t::layout_t::template at<0>() == -1), …
> updated asserts

- src/dawn/IIR/MultiStage.cpp
- src/dawn/IIR/Stage.cpp
- src/dawn/IIR/Stencil.cpp
Changes -fpass-verbose behavior when dumping json nodes of Stencil, MultiStage or Stage. Instead of outputting dictionaries, it gives arrays of (respectively) MultiStages, Stages and DoMethods.
#180 
```
// RUN: %gtclang% %file% -fpass-verbose
#include "gridtools/clang_dsl.hpp"
stencil test {
storage a, b ;
storage_ij c;
Do {
c = b[i+2] + a[j-3];
a = c[i+1];
}
}
};
```
Generated log file PassInlining_1_Log.json now looks like:
```
...
"Stencil0": {
...
"MultiStages": [
{
"Caches": null,
"Fields": ...,
"ID": 38,
"Loop": "parallel",
"Stages": [
{
"DoMethods": [
{
"Fields": null,
"ID": 1,
"Stmts":  ...
}
],
"Extents": "[(0, 0), (0, 0), (0, 0)]",
"Fields": ...,
"RequiresSync": false
},
{
"DoMethods": [
{
"Fields": null,
"ID": …
```
> change json dump of -fpass-verbose to produce arrays 

- src/dawn/IIR/FieldAccessMetadata.cpp
- src/dawn/IIR/FieldAccessMetadata.h
- src/dawn/IIR/StencilInstantiation.cpp
- src/dawn/IIR/StencilMetaInformation.cpp
- src/dawn/IIR/StencilMetaInformation.h
- src/dawn/Serialization/IIRSerializer.cpp
- test/unit-test/dawn/IIR/TestIIRSerializer.cpp
- Field-Versioning had a very odd way of storing things that made the fix of https://github.com/MeteoSwiss-APN/dawn/issues/121 impossible
- This was already looked at in  https://github.com/MeteoSwiss-APN/dawn/pull/187 but is now reworked here
- This changes the indexing to be 0-based instead of 1-based and therefore need to go with https://github.com/MeteoSwiss-APN/gtclang/pull/134
Since the indexing changes to be 0 based instead of 1 based, we need to adapt some reference files and the testing is in https://github.com/MeteoSwiss-APN/gtclang/pull/134
> Fix fieldversioning

- src/dawn/Optimizer/PassStageSplitter.cpp
Since, for now, the stage splitting inside an if block doesn't work, this code adds a check for cases in which this would happen, reports a diagnostic message and returns error.
Also the `oldGraph` uninitialized pointer bug is fixed here. However the code that dumps dependency graphs for each split should be refactored in a different PR.
#190 
```
#include "gridtools/clang_dsl.hpp"
globals {
bool x = false;
};
stencil_function sum {
offset off;
storage data;
Do { return data[off] + data; }
};
stencil test {
storage b,c,d;
var z, a;
Do {
vertical_region(k_end, k_end) {
if(x == 0) {
z = a * b;
const double e = d * (c * sum(i + 1, z));
}
}
}
};
```
> Add diagnostic error for unsupported Read-before-Write conflict inside if block

- src/dawn/IIR/MultiStage.cpp
- src/dawn/IIR/StencilMetaInformation.cpp
Changes insertions into json object of the form `jsonObj[integerVar]` (which force the json object to be an array without `integerVar` necessarily being a valid array index) into `jsonObj[std::to_string(integerVar)]`.
Crash when compiling the following code with ` -fpass-verbose`:
```
#include "gridtools/clang_dsl.hpp"
globals {
bool x = false;
};
stencil_function sum {
offset off;
storage data;
Do { return data[off] + data; }
};
stencil test {
storage b,c,d;
var z, a;
Do {
vertical_region(k_end, k_end) {
if(x == 0) {
a = 0;
z = a * b;
const double e = d * (c * sum(i + 1, z));
}
}
}
};
```
> Fix json dump access by index bug

- src/dawn/Optimizer/PassDataLocalityMetric.cpp
- src/dawn/Optimizer/PassDataLocalityMetric.h
When `ReportDataLocalityMetric` is on, PassDataLocalityMetric run method was trying to create a padding string filled with '-' possibly giving a negative number as fill size. Fixed by imposing that the fill size must be non-negative.
Bug was happening for long stencil names such as: HorizontalDiffusionColdPoolTPCopyStencil
> Fixes dash filling bug

- scripts/jenkins/env_kesch.sh
Using the latest gcc (6) was bad idea, since many other software is built (like clang) using the default 5.4
> move gcc to 5.4

- src/dawn/IIR/IIRNodeIterator.h
There was a default constructor setting it's const-ptr to a nullptr and should therefore never be used. This makes them private. (Solution by @Stagno)
Cleanup of the node iterator class.
> Nodeiteator cleanup

- bundle/CMakeLists.txt
- scripts/jenkins/build.sh
Changes the default behavior of the bundle to not run the python examples as the default is not to install the required python modules.
This should fix the currently broken master builds of jenkins.
If the bundle downloads dawn, the default flags are off for python-bindings but on for python tests. So the (post)-install step fails. 
http://jenkins-mch.cscs.ch/view/PASCHA/job/gtclang/
The pipeline test does not work here since it works with a dawn that is installed on a previous step. So a "maunal" launch of the pipeline https://github.com/MeteoSwiss-APN/gtclang/pull/146
This PR is indepdent
> Fix pytests

- src/dawn/IIR/Stage.cpp
- src/dawn/Optimizer/PassStageMerger.cpp
Moves the axis computation to the stencil-level so we're not computing illegal states
Issue with the integration-tests when both dawn and gtclang are used in debug mode
https://github.com/MeteoSwiss-APN/gtclang/blob/master/test/integration-test/CodeGen/intervals_stencil.cpp
> Fix stage merge

- src/dawn/Serialization/IIRSerializer.cpp
We remove all the backwards dependencies from the Seriaizer to the Optimizer. This is part of cleaning up all unwanted (circular) dependencies between modules
Now Serializer is independent of Optimizer
> Fix Serializer -> Optimizer dependency

- src/dawn/Compiler/DawnCompiler.cpp
Restores performance to before this bug was introduced
Performance issues encountered starting 8/20
\<jenkins\>/view/PASCHA/job/cosmo-prerelease-gtclang_perftest_daily/
This PR is indepenedent
> restore performance

- python/dawn/sir.py
- python/dawn/test_sir.py
Due to changes in SIR and AST structure these tests were failing.
> Updating python tests

- examples/python/copy_stencil.py
- examples/python/hori_diff.py
- examples/python/tridiagonal_solve.py
The verbose mode of the python examples is broken due to renaming
makes the verbose mode of the example works (baused on Joerg's feedback)
```
cd dawn/bundle/install/examples/python
export PYTHONPATH=dawn/bundle/install/python
python3.7 copy_stencil.py -v
```
> Fix python examples

- src/dawn/IIR/StencilMetaInformation.cpp
- src/dawn/Optimizer/OptimizerContext.cpp
- src/dawn/Optimizer/StatementMapper.cpp
- test/unit-test/dawn/IIR/TestIIRSerializer.cpp
Some edge cases in the clang-gridtools test suite were not correctly handled by the changes introduced due to the fix to issue_199 (`DoubleSidedMap` and general `StencilMetaData` clean up). `AccessID` s to literals are now always strictly negative, no matter the context (e.g. even if the literal is in fact a global which was overwritten by a config file). A test was adapted accordingly.
> Fix tests in clang-gridtools due to issue_199

- src/dawn/SIR/SIR.cpp
Since type is not explicitly serialized for globals, this makes it always known.
```
globals {
bool ltur;
double zdtr = 0.8;
...
}
```
becomes, in SIR:
```
"global_variables": {
"ltur": {
"is_constexpr": false,
"boolean_value": false
},
"zdtr": {
"is_constexpr": false,
"double_value": 0.8
}, ...
```
> Add default value to globals

- CMakeLists.txt
- cmake/DawnMacros.cmake
- src/dawn/Support/DoubleSidedMap.h
- test/unit-test/dawn/IIR/TestIIRSerializer.cpp
and fix
- use-after-free in DoubleSidedMap
- memory leak in unittest
> Enable address sanitizer in Debug mode

- examples/python/copy_stencil.py
- examples/python/hori_diff.py
- examples/python/tridiagonal_solve.py
For ctypes to work properly, the return type and argument types have to be specified. Fixes #250.
> Python examples: Add function signature for ctypes calls

- .github/pull_request_template.md
This adds a template for all PR's.
This PR is also happening in GTClang: (https://github.com/MeteoSwiss-APN/gtclang/pull/171) and Clang-GT (https://github.com/MeteoSwiss-APN/clang-gridtools/pull/128)
This should unify the description we're giving in PR's
This does not touch any functionality. No tests required
> PR-Template

- dawn/scripts/check_modularization/check_modularization.sh
- scripts/git_hooks/check_modularization
- scripts/git_hooks/pre-commit
Adds the `check_modularization.sh`-script from GridTools. Complains if we have unexpected dependencies between the modules defined in #238
> Add check_modularization script

- dawn/prototype/mylibDriver.cpp
- dawn/src/dawn/IIR/AccessUtils.h
- scripts/clang_format_all.sh
- scripts/ignore_list.sh
Fixes the format-all script
`./scripts/clang_format_all.sh`
> Fix format all

- gtclang/src/gtclang/Support/ASTUtils.h
- gtclang/src/gtclang/Support/ClangCompat/ImplicitNodes.h
Support for clang 9.
`skipImplicitNodes()` is moved from Stmt down to Expr.
> Support for clang 9

- dawn/src/dawn/SIR/SIR.cpp
- dawn/src/dawn/SIR/SIR.h
This removes the custom sir::Value in favor of using the std::variant container. Fixes #293.
> Refactor sir::Value using std::variant

- dawn/cmake/modules/DawnProtobufGenerate.cmake
- dawn/scripts/jenkins/build.sh
- dawn/src/dawn/IIR/CMakeLists.txt
Sets a dependency between the SIR protobuf files and the IIR protobuf files which depend on the former. (Actually not for generating them, but for using the IIR header.)
Fixes #323.
> Fix race condition in CMake between IIR and SIR generated protobuf

- dawn/src/dawn/Unittest/IIRBuilder.cpp
The location type is already added in `addField`. Doing this twice leads to an assert.
> Fix assert in unstructured IIR Builder

- dawn/src/dawn/AST/Offsets.h
- dawn/src/dawn/CodeGen/Cuda/CacheProperties.cpp
- dawn/src/dawn/IIR/Extents.cpp
- dawn/src/dawn/IIR/Extents.h
- dawn/src/dawn/IIR/MultiStage.cpp
- dawn/test/unit-test/dawn/AST/CMakeLists.txt
- dawn/test/unit-test/dawn/AST/TestMain.cpp
- dawn/test/unit-test/dawn/AST/TestOffset.cpp
- dawn/test/unit-test/dawn/IIR/TestExtent.cpp
Extents and offsets are now default constructible. The default constructor creates a null offset/extent that can be used with and transformed into an unstructured and/or cartesian offset/extent. This is very helpful for generic passes that need to be able to create offsets/extents, but are not aware of the grid type.
- Adds default constructor for offset
- Adds default constructor for extent
- Adds tests for Offset class
- Improve tests for Extent class
resolves #369
```
Extents my_extent{};
Extents cartesian_extent{ast::cartesian};
auto added_extent = my_extent + cartesian_extent;
auto const& hExtent = extent_cast<CartesianExtent const&>(added_extent.horizontalExtent());
// throws bad_cast when unstructured extents are implemented:
// auto const& hExtent = extent_cast<UnstructuredExtent …
```
> Default constructible Offsets and Extents

- gtclang/src/gtclang/Support/ClangCompat/CompilerInvocation.h
- gtclang/src/gtclang/Support/ClangCompat/FileUtil.h
Fix compilation with clang 9. I can still not use gtclang built with llvm 9, but at least it compiles.
Regression from #344
> Fix compilation for GTClang with LLVM 9

- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.cpp
Adds `gridtools::` namespace to `update_global_parameter` call in `update_globals`.
Resolves a build failure.
> Add namespace to update_global_parameter in GTCodeGen.cpp

- dawn/src/dawn/IIR/StencilMetaInformation.h
In [StencilFunctionAsBCGenerator](https://github.com/MeteoSwiss-APN/dawn/blob/462107cf58910e1734e20a671214452c6ad5c13a/dawn/src/dawn/CodeGen/StencilFunctionAsBCGenerator.cpp#L51) we took a reference from the member of a temporary. For some compilers this resulted in garbage values in the generated code.
Now we return a reference instead of a value.
> Fix dangling reference

- dawn/.clang-tidy
- dawn/cmake/DawnMacros.cmake
- dawn/src/dawn-c/Options.cpp
- dawn/src/dawn-c/util/Allocate.h
- dawn/src/dawn/IIR/MultiStage.cpp
- dawn/src/dawn/IIR/StencilInstantiation.cpp
- dawn/src/dawn/Optimizer/PassDataLocalityMetric.cpp
- dawn/src/dawn/Optimizer/PassSSA.cpp
- dawn/src/dawn/Optimizer/PassTemporaryType.cpp
- dawn/src/dawn/Optimizer/Replacing.cpp
- dawn/src/dawn/Optimizer/Replacing.h
- dawn/src/dawn/Optimizer/StatementMapper.cpp
- dawn/src/dawn/Optimizer/TemporaryHandling.cpp
- dawn/src/dawn/Support/ArrayRef.h
- dawn/src/dawn/Support/EditDistance.h
- dawn/test/unit-test/dawn/Support/TestSmallVector.cpp
- gtclang/cmake/GTClangMacros.cmake
Adds a minimal `.clang-tidy` config file (created with `clang-tidy -dump-config`) to dawn. Fix several warnings and disable some.
Adds `-fsanitize=address,undefined` to dawn and gtclang in debug mode.
> Fix clang-tidy warnings

- dawn/prototype/README
- dawn/prototype/atlasDiffusionDriver.cpp
- dawn/prototype/atlasVerticalSumDriver.cpp
- dawn/prototype/atlas_interface.hpp
- dawn/prototype/mylib.cpp
- dawn/prototype/mylib.hpp
- dawn/prototype/mylibCopyDriver.cpp
- dawn/prototype/mylibDiffusionDriver.cpp
- dawn/prototype/mylibVerticalSumDriver.cpp
- dawn/prototype/mylib_interface.hpp
- dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
- dawn/src/dawn/Unittest/IIRBuilder.h
- dawn/test/unit-test/dawn-c/TestCompiler.cpp
This PR now uses the k-offsets introduced previously. That is, vertical offsets are now used in the code generation of `CXXNaiveIco`. NOTE: This currently breaks `lukaslib` compatibility.
Fixes #412 
A test was introduced to the deactivated c-tests. Follow the `README` in dawn/prototype to generate and run stencil code that uses the k-offsets. (verticalSum / verticalSumDriver)
> unstructured k offsets

- dawn/test/integration-test/reference_iir/update_references.sh
- dawn/test/unit-test/dawn/Optimizer/Passes/update_references.sh
- gtclang/test/integration-test/update_references.sh
Adds update scripts for all generated references in dawn and gtclang. 
All scripts try to guess the proper paths from yoda and normal build, otherwise, the options can be provided.
Try to change some references and then run the update scripts.
> add reference update scripts

- gtclang/.gitignore
- gtclang/test/integration-test/CMakeLists.txt
- gtclang/test/integration-test/FV3/Options.cpp
- gtclang/test/integration-test/FV3/Options.hpp
- gtclang/test/integration-test/FV3/TestMain.cpp
- gtclang/test/integration-test/FV3/p_grad_c.cpp
- gtclang/test/integration-test/FV3/p_grad_c_benchmark.cpp
- gtclang/test/integration-test/FV3/p_grad_c_benchmark.cu
Adds an FV3 stencil to the gtclang tests and sets up the integration test infrastructure for more to come later. To enable this, the cmake functions `code_generate_examples` and `code_compile_examples` were altered to add a `DIRECTORY` argument. The new test is automatically built when `GTCLANG_BUILD_GT_CPU_EXAMPLES` is enabled.
Resolves #442.
The test added so far is `p_grad_c` from `FV3/atmos_cubed_sphere/model/dyn_core.F90`.
> Add p_grad_c integration test

- dawn/bundle/CMakeLists.txt
- dawn/cmake/modules/DawnProtobufGenerate.cmake
Skips setting LD_LIBRARY_PATH in `run_protobuf.sh` now that Protobuf is linked statically.
This requires merging #20 in MeteoSwiss-APN/yoda.
> Build with static protobuf library

- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.cpp
- dawn/src/dawn/IIR/StencilFunctionInstantiation.cpp
- scripts/clang_format_all.sh
- scripts/git_hooks/pre-commit
- scripts/ignore_list.sh
Fix `pre-commit` which was not using the ignore list (regular expressions) defined by `ignore_list.sh`. Also fixes such list which was incorrect as it assumed that the file paths outputted by `git diff-index` were of the form `./dawn/something`, while they actually are like `dawn/something`.
> Fix pre-commit ignore list

- gtclang/cmake/GTClangOptions.cmake
- gtclang/scripts/jenkins/build.sh
- gtclang/test/atlas-integration-test/CMakeLists.txt
If atlas is not found, tests are not run (but a cmake warning will pop up), unless the `GTCLANG_FORCE_ATLAS_INTEGRATION_TESTS` flag is set to ON, which will trigger an error.
Default for this flag is OFF.
> Make atlas optional unless flag to force running tests is set

- dawn/src/dawn/Optimizer/PassSetStageGraph.cpp
- gtclang/test/integration-test/PassStageMerger/Test07.cpp
- gtclang/test/integration-test/PassStageMerger/Test07_after_ref.json
- gtclang/test/integration-test/PassStageMerger/Test07_before_ref.json
This fixes the greedy reorder strategy to do what we expect in the write after write case
Fixes illegal execution order
```
stencil Test {
storage in, out;
Do {
out = in;
}
out = 0;
}
}
};
```
> fix to reordering strategy

- dawn/src/dawn/IIR/DoMethod.cpp
- dawn/src/dawn/Optimizer/Renaming.cpp
- gtclang/test/integration-test/PassPreprocessor/BracketAccessTest.cpp
- gtclang/test/integration-test/PassPreprocessor/DoMethodTest.cpp
- gtclang/test/integration-test/PassPreprocessor/VerticalRegionTest.cpp
- gtclang/test/integration-test/PassSetCaches/KCacheTest02b.cpp
- gtclang/test/integration-test/PassSetCaches/KCacheTest03.cpp
- gtclang/test/integration-test/PassSetCaches/KCacheTest04.cpp
- gtclang/test/integration-test/PassSetCaches/KCacheTest06.cpp
- gtclang/test/integration-test/PassTemporaryType/PromoteTest01.cpp
- gtclang/test/integration-test/PassTemporaryType/PromoteTest02.cpp
- gtclang/test/integration-test/PassTemporaryType/PromoteTest03.cpp
- gtclang/test/integration-test/PassTemporaryType/PromoteTest04.cpp
- gtclang/test/integration-test/PassTemporaryType/PromoteTest05.cpp
- gtclang/test/utils/gtclang-tester/gtclang_tester/runner.py
The names stored in the expressions are now the used ones instead of the user provided ones
See example output
```
#include "gtclang_dsl_defs/gtclang_dsl.hpp"
stencil A {
storage in_field, out_field;
Do {
double ee = in_field + 5;
out_field = ee;
}
}
};
```
now prints:
```
StencilInstantiation : A
Stencil_0
{
MultiStage_0 [parallel]
{
Stage_0
{
Do_0 { Start : End }
{
float_type __local_ee_31 = (in_field[<no_horizontal_offset>,0] + 5);
Write Accesses:
__local_ee_31 : [<no_horizontal_extent>,(0,0)]
Read Accesses:
5 : [<no_horizontal_extent>,(0,0)]
in_field : [<no_horizontal_extent>,(0,0)]
out_field[<no_horizontal_offset>,0] = __local_ee_31;
Write Accesses:
out_field : [<no_horizontal_extent>,(0,0)]
Read Accesses: …
```
> Fix Names of local variables

- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.cpp
- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.h
The constructor of `gridtools::grid` is not part of the public API (indicated by the fact that it changed from v1.0 to v1.1). Thus, dawn should use `gridtools::make_grid` which is public API to create the grid.
GT4Py uses Gridtools 1.1.
> Use `make_grid` in the generated code

- dawn/scripts/jenkins/env_daint.sh
- dawn/scripts/jenkins/env_kesch.sh
- gtclang/scripts/jenkins/env_daint.sh
- gtclang/scripts/jenkins/env_kesch.sh
Protobuf gets now installed in `/project/c14/install/daint/protobuf/`. Previously it was installed in `/scratch/snx3000`, which gets wiped once in a while.
> Point to new protobuf install location

- _sources/coding.txt
This is the PR to update our coding conventions. Some points left open before are now further clarified. 
* east vs. west const was left open for now, since there seems to be a `clang-format` rule for this [in the near future](https://reviews.llvm.org/D69764), making the point obsolete.
* I agree that a naming convention for template parameters would be nice to improve legibility. Currently most of the template parameters we use (which aren't simply `T`) start with an uppercase letter, clashing with the convention for class names. Maybe it would be reasonable to have all template parameters start with `T`? This is already respected in parts of the code, e.g. in `dawn/IIR/IIRNode.h` which uses  `template <typename TNodeType>`, `template <typename TParent, typename TChild>` etc.
> Coding Conventions

- dawn/src/dawn/IIR/DoMethod.cpp
Fixes an issues with the replacement of names in `VarAccessExpr`. 
```
Do {
vertical_region(k_start, k_start) {
double gav = -0.5 * wcon;
double as = gav * BET_M;
}
}
```
used to to lead to wrong names in the IIR:
`float_type __local_as_43 = (gav * (float_type 0.5 * (float_type 1 - float_type 0)));`
this is now correct:
`float_type __local_as_43 = (__local_gav_41 * (float_type 0.5 * (float_type 1 - float_type 0)));`
> fixed VarDeclStmt visitor

- dawn/scripts/jenkins/build.sh
Jenkins used to use the standard pip instead of the one in the virtual environment which led to permission errors
Fixes the currently broken plans on master
This is independent
> fix pip calls to use the venv

- dawn/src/dawn/Optimizer/PassComputeStageExtents.cpp
Discussions showed that Stages that have a specified horizontal extent should never be extended to fit for additional computation
Fixes #472
```
#include "gtclang_dsl_defs/gtclang_dsl.hpp"
using namespace gtclang::dsl;
stencil Test {
storage in, out, out2;
void Do() {
iteration_space() {
// computation
out = in;
}
iteration_space(i_start, i_start + 1) {
// correction term
out = 3;
}
// use of conputed value
out2 = out[i + 1] + out[i - 1] + out[j - 1] + out[j + 1];
}
}
};
```
This PR is independent, for the test, use the front end branch https://github.com/MeteoSwiss-APN/dawn/pull/531
> stages with defined extents do not extend their computational domain

- dawn/test/integration-test/CMakeLists.txt
- dawn/test/unit-test/dawn-c/CMakeLists.txt
- dawn/test/unit-test/dawn/AST/CMakeLists.txt
- dawn/test/unit-test/dawn/IIR/CMakeLists.txt
- dawn/test/unit-test/dawn/Optimizer/CMakeLists.txt
- dawn/test/unit-test/dawn/Optimizer/Passes/CMakeLists.txt
- dawn/test/unit-test/dawn/Optimizer/Passes/TestMain.cpp
- dawn/test/unit-test/dawn/Optimizer/TestsFromSIR/CMakeLists.txt
- dawn/test/unit-test/dawn/Optimizer/TestsFromSIR/TestMain.cpp
- dawn/test/unit-test/dawn/SIR/CMakeLists.txt
- dawn/test/unit-test/dawn/Support/CMakeLists.txt
- gtclang/test/unit-test/Frontend/CMakeLists.txt
- gtclang/test/unit-test/Support/CMakeLists.txt
- gtclang/test/unit-test/Unittest/CMakeLists.txt
Adds each individual Google test to ctest.
Gives output like this:
```
Start 163: DawnUnittestSIR::SIRStencilFunctionTest.AST
...
Total Test time (real) =  13.14 sec
The following tests did not run:
64 - DawnUnittestOptimizerPasses::StencilSplitAnalyzer.test_no_bc_inserted (Disabled)
65 - DawnUnittestOptimizerPasses::StencilSplitAnalyzer.test_unused_bc (Disabled)
66 - DawnUnittestOptimizerPasses::StencilSplitAnalyzer.test_bc_extent_calc (Disabled)
67 - DawnUnittestOptimizerPasses::StencilSplitAnalyzer.test_two_bc (Disabled)
412 - DawnCUnittest::CompilerTest.CodeGenSumEdgeToCells (Disabled)
413 - DawnCUnittest::CompilerTest.SumVertical (Disabled)
414 - DawnCUnittest::CompilerTest.CodeGenDiffusion (Disabled)
415 - DawnCUnittest::CompilerTest.CodeGenTriGradient (Disabled)
416 - …
```
> Split tests using gtest_discover_tests

- gtclang/CMakeLists.txt
If you have the CUDA toolkit but no GPU, certain tests are failing. Setting this option in CMake allows you to disable CUDA tests.
> Add ENABLE_CUDA_IF_FOUND option

- dawn/src/dawn/Compiler/DawnCompiler.cpp
- dawn/src/dawn/Support/FileSystem.h
Use std::experimental::filesystem if std::filesystem is not supported, i.e. gcc < 8.
> Use experimental::fs if fs is not supported

- .clang-tidy
Clang 9 complains about the 'User' key not having a value. For example, from the vscode log:
```YAML:8:1: error: unexpected scalar
CheckOptions:
^
Error parsing /Users/johannd/Code/dawn/dawn/.clang-tidy: Invalid argument
```
Is there a reason not to have this in the root directory? This PR moves it there.
> Move clang-tidy and remove 'User' key

- dawn/src/dawn4py/serialization/test/test_sir.py
- dawn/src/dawn4py/serialization/utils.py
- dawn/test/unit-test/test_dawn4py/utils.py
- Add support for weights to reduction in dawn4py
- Add test for `make_reduction_over_neighbor_expr`
> Add support for weights to reduction in dawn4py

- dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
- dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.h
- dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
- dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.h
- dawn/src/dawn/CodeGen/CodeGen.cpp
- dawn/src/dawn/CodeGen/CodeGen.h
- dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.h
- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.cpp
- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.h
- dawn/src/dawn/Compiler/DawnCompiler.cpp
- dawn/src/dawn/Compiler/DawnCompiler.h
Adds a generate method to DawnCompiler and calls it from compile(). This is in preparation for splitting code generation tests from the gtclang integration tests. 
Part of #625.
This is implicitly tested because compile() calls it.
> Add generate method to DawnCompiler

- dawn/src/dawn/Compiler/DawnCompiler.cpp
- dawn/src/dawn/IIR/CMakeLists.txt
- dawn/src/dawn/IIR/LocalVariable.cpp
- dawn/src/dawn/IIR/LocalVariable.h
- dawn/src/dawn/IIR/StencilMetaInformation.cpp
- dawn/src/dawn/IIR/StencilMetaInformation.h
- dawn/src/dawn/Optimizer/CMakeLists.txt
- dawn/src/dawn/Optimizer/PassInlining.cpp
- dawn/src/dawn/Optimizer/PassLocalVarType.cpp
- dawn/src/dawn/Optimizer/PassLocalVarType.h
- dawn/src/dawn/Optimizer/StatementMapper.cpp
- dawn/src/dawn/Optimizer/TemporaryHandling.cpp
- dawn/src/dawn/Unittest/IIRBuilder.cpp
- dawn/src/dawn/Unittest/IIRBuilder.h
- dawn/src/dawn/Validator/GridTypeChecker.cpp
- dawn/test/unit-test/dawn/Optimizer/Passes/CMakeLists.txt
- dawn/test/unit-test/dawn/Optimizer/Passes/TestPassLocalVarType.cpp
- dawn/test/unit-test/dawn/Validator/TestGridTypeChecker.cpp
- Add `LocalVariableData` (data container for a local variable) and `LocalVariableType` which can be `Scalar, OnCells, OnEdges, OnVertices, OnIJ`.
- Add pass (and unit tests) `PassLocalVariableType` to determine the type of a local variable.
- Add map from access ID of variable to `LocalVariableData` in metadata (not serialized).
- Add helper method `StencilMetaInformation::declareVar()` to declare a variable (same as `StencilMetaInformation::addStmt()` but doesn't require a `VarDeclStmt` in input).
- In `GridTypeChecker` check if all variable types match the grid type.
resolves #669
> Implementation of PassLocalVarType

- dawn/src/dawn/Unittest/CompilerUtil.cpp
- dawn/src/dawn/Unittest/CompilerUtil.h
- dawn/src/dawn/Unittest/IIRBuilder.cpp
- dawn/src/dawn/Unittest/IIRBuilder.h
- dawn/test/integration-test/serializer/GenerateInMemoryStencils.cpp
- dawn/test/integration-test/unstructured/GenerateUnstructuredStencils.cpp
- dawn/test/unit-test/dawn-c/TestCompiler.cpp
- dawn/test/unit-test/dawn/IIR/TestIIRSerializer.cpp
- dawn/test/unit-test/dawn/Optimizer/Passes/TestPassCaching.cpp
- dawn/test/unit-test/dawn/Optimizer/Passes/TestPassLocalVarType.cpp
- dawn/test/unit-test/dawn/Validator/TestGridTypeChecker.cpp
Return `shared_ptr<StencilInstantiation>` from `IIRBuilder.build()`.
Reason:
- By design of the `IIRBuilder.build()`, the `StencilInstantiationContext` always contained exactly one `StencilInstantiation`. 
- The `shared_ptr<>` should be removed.
> Return StencilInstantiation from IIRBuilder

- dawn/test/unit-test/dawn-c/TestCompiler.cpp
Fixes call to `dumpNaiveIco()`.
> Fix dump call

- dawn/src/dawn/Optimizer/PassTemporaryMerger.cpp
- dawn/src/dawn/Optimizer/Renaming.cpp
- dawn/test/unit-test/dawn/Optimizer/Passes/TestPassTemporaryMerger.cpp
`PassTemporaryMerger` merges temporaries into the one with lowest access id. Since access ids vary from compiler to compiler, tests failed on some dev setups (e.g. gcc 9.2.1). This PR fixes this by selecting the first temporary in alphabetical order as the target one.
> Quick fix of PassTemporaryMerger

- gtclang/src/gtclang/Driver/CompilerInstance.cpp
Adds correct include path for GCC on MacOS. Code is only changed inside an __APPLE__ macro check.
> Fix for GCC on MacOS

- dawn/src/driver-includes/storage_runtime.hpp
Enables gt4py (and other consumers of generated GridTools code) to select the backend. This is a hacky, but a proper solution is out-of-scope of this task. See comment in code and issue #747.
> Gt4py: workaround backend selection

- dawn/src/dawn/Serialization/IIRSerializer.cpp
- dawn/src/dawn/Serialization/IIRSerializer.h
- dawn/test/unit-test/dawn/IIR/TestIIRSerializer.cpp
Removes redundant IIR deserialization methods that accept OptimizerContext parameters that were not used.
Resolves #668
> Remove redundant IIRSerializer deserialization method

- dawn/src/CMakeLists.txt
- dawn/src/dawn/IIR/CMakeLists.txt
- dawn/src/dawn/SIR/CMakeLists.txt
The proto header files were still not being correctly installed. This PR fixes that.
> Correctly install IIR and SIR generated proto headers

- dawn/src/dawn/Optimizer/PassLocalVarType.cpp
- dawn/test/unit-test/dawn/Optimizer/TestPassLocalVarType.cpp
PassLocalVarType wasn't looking inside the conditions of nested if statements to register variable dependencies in order to guess their types. This fixes it.
As I'm not yet sure how to transform the unit tests of this pass to start from IIR and have a way to regenerate the input IIR, the 4 new tests of this PR follow the same pattern used before. Once the procedure is clarified, they will be all converted at once.
> Quick fix for nested ifs

- dawn/src/dawn4py/_dawn4py.cpp
- dawn/test/integration-test/dawn4py-tests/data/copy_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/hori_diff_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/tridiagonal_solve_stencil_ref.cpp
The include is already part of the pp_defines_list. Especially adding the explicit include here breaks unstructured (introduces unnecessary dependency to gridtools).
> Remove extra include in dawn4py

- dawn/src/dawn4py/serialization/utils.py
This PR resolves the following GT4Py errors in the SIR serialization step in the Dawn4Py integration that occur in the FV3 stencils:
```python
File "/home/eddied/Work/dawn/dawn/src/dawn4py/serialization/utils.py", line 357, in make_stmt
raise SIRError("cannot create Stmt from type {}".format(type(stmt)))
dawn4py.serialization.error.SIRError: cannot create Stmt from type <class 'SIR.statements_pb2.Field'>
```
... and ...
```python
File "/home/eddied/Work/dawn/dawn/src/dawn4py/serialization/utils.py", line 722, in make_literal_access_expr
builtin_type.type_id = type
AttributeError: 'BuiltinType' object attribute 'type_id' is read-only
```
> Fix Dawn4Py SIR serialization utils to work with GTPy

- dawn/src/dawn/IIR/Stage.cpp
- dawn/src/dawn/IIR/Stage.h
- dawn/src/dawn/IIR/proto/IIR/IIR.proto
- dawn/src/dawn/Serialization/IIRSerializer.cpp
- dawn/test/unit-test/dawn/IIR/TestIIRSerializer.cpp
This PR updates the Protobuf definitions for IIR stages to include i-range and j-range intervals for global iteration spaces, and modifies the IIRSerializer accordingly.
Resolves #819
> Add iteration space ranges to IIR stage prototypes

- dawn/src/dawn/Optimizer/PassValidation.cpp
- dawn/src/dawn/Optimizer/TemporaryHandling.cpp
- dawn/src/dawn/Unittest/IIRBuilder.cpp
- dawn/src/dawn/Validator/GridTypeChecker.h
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.h
- dawn/test/unit-test/dawn/Validator/TestUnstructuredDimensionChecker.cpp
- Add stage location type consistency check in `UnstructuredDimensionChecker` to check stage's location type consistency w.r.t. the statements inside the stage.
- Make methods of `UnstructuredDimensionChecker` and `GridTypeChecker` static.
- Improve error reporting of `UnstructuredDimensionChecker` (line number reporting).
resolves #592
> Add stage location type consistency checks to validation pass

- dawn/src/dawn/Compiler/DawnCompiler.cpp
- gtclang/src/gtclang/Frontend/GTClangASTConsumer.cpp
Calls dawn components separately from gtclang, in order to recognize the `-disable-optimization` gtclang flag, since calling separately does not add default pass groups when none are present.
Also deletes a bit of unnecessary code.
> Fix gtclang dawn call

- dawn/src/dawn/SIR/SIR.h
- dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cu
This PR changes the SIR global variables map from unordered to ordered to ensure that the same backend code is always generated.
> Change global variable map from unordered to ordered

- dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.h
- dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda/MSCodeGen.h
- dawn/test/unit-test/dawn/CodeGen/reference/global_indexing.cu
This PR modifies the CudaCodeGen backend to copy global indices and offsets to device memory before the kernel call and frees it afterward.
Resolves #865
> Fix global iteration space bug in CUDA backend

- dawn/src/dawn/Optimizer/PassOptions.inc
- dawn/src/dawn4py/_dawn4py.cpp
- dawn/test/integration-test/dawn4py-tests/data/copy_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/hori_diff_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/tridiagonal_solve_stencil_ref.cpp
- gtclang/src/gtclang/Driver/Options.inc
- gtclang/src/gtclang/Frontend/GTClangASTConsumer.cpp
This ensures the use of `-no-opt` and `-default-opt` do the correct thing. 
The new interface does:
- run the default group if nothing is specified
- run only the selected passes if they are specified
- run nothing if `-no-opt` is specified
- run default plus passes if both are specified
- asserts if `no-opt` and optimization is specified
Issues with current implementation of the flag check while maintaining backwards compatibility.
This requires the default flag to be set in one of Clang-GT's tests, so testing is here:
http://localhost:8080/job/dawn_gtclang_clang-gridtools_PR/415/
> Fixing flag usage in gtclang

- .gitignore
- dawn/src/dawn/Compiler/DawnCompiler.cpp
- dawn/src/dawn/Serialization/IIRSerializer.cpp
- dawn/src/dawn/Serialization/SIRSerializer.cpp
- dawn/src/dawn/dawn-opt.cpp
Correctly try-catch with dawn-opt. Involves removing incorrect `dawn_unreachable(...)` calls and replacing these with throws. The serialization functions should no longer use `dawn_unreachable(...)` in the future.
> Try-catch correctly with dawn-opt

- dawn/CMakeLists.txt
Use consistent python version for dawn and pybind11.
> Consistent python version

- dawn/src/dawn/dawn-opt.cpp
- gtclang/src/gtclang/gtc-parse.cpp
Skip serialization if certain options are present in separate executables. Mimics the existing gtclang behavior.
> Skip serialization in certain cases

- dawn/CMakeLists.txt
- gtclang/test/integration-test/IIRSerializer/AccessTest_ref.iir
- gtclang/test/integration-test/IIRSerializer/CopyTest_ref.iir
- gtclang/test/integration-test/IIRSerializer/NestedStencils_ref.iir
- gtclang/test/integration-test/IIRSerializer/StencilFnCallTest_ref.iir
- gtclang/test/integration-test/Regression/globals_dependencies_issue401_ref.0.iir
Updates IIR reference files in the `GTClang::Integration` tests to reflect the change that the default multistage loop order is specified by the user.
> Update loop orders in IIR reference files

- dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda/MSCodeGen.h
This PR modifies the `MSCodeGen` class to only declare global CUDA variables and functions once per translation unit, rather than once per kernel.
Resolves #939
> Declare cuda globals once

- gtclang/src/gtclang/Frontend/GTClangIncludeChecker.h
Add header to GTClangIncludeChecker, required for LLVM 10.
> Add header to GTClangIncludeChecker

- dawn/src/dawn/CodeGen/CMakeLists.txt
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.h
- dawn/src/dawn/CodeGen/Cuda-ico/LocToStringUtils.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/LocToStringUtils.h
- dawn/src/dawn/CodeGen/Cuda/CodeGeneratorHelper.cpp
- dawn/src/dawn/CodeGen/Cuda/CodeGeneratorHelper.h
- dawn/src/dawn/CodeGen/Driver.cpp
- dawn/src/dawn/CodeGen/Options.h
- dawn/src/dawn/dawn-codegen.cpp
- dawn/src/driver-includes/cuda_utils.hpp
This PR introduces a simple code gen for unstructured (icosahedral) cuda code. The code gen only supports the feature set used by the two ICON Laplacians so far, which can roughly be summarized as
* dense and sparse fields on location(chains)
* loop concept to fill sparse fields
* reduction over neighbor(chains)
Nested reductions etc. are not supported. It is also assumed that each stage runs over the all k levels (the full vertical dimension). 
Fixes #945 
There is currently no (automated) testing of the code gen since we expect the code gen to heavily change in the near future. It can be manually tested using a adapted driver code for the diamond found [here](https://github.com/mroethlin/cuda_stencil/tree/codegen_experiment).
> Add Cuda Code Gen for Unstructured Meshes 

- dawn/setup.py
- dawn/src/dawn/CMakeLists.txt
* Fix adding -lstdc++fs for gcc 8
On ubuntu 18.04, gcc8.4.0, cmake 3.16.2: CMAKE_COMPILER_IS_GNUCC is not set 
* install the interface with setup.py as external sources for dawn4py
> add stdc++fs also for GNU CXX compiler

- dawn/setup.py
Allow setting BUILD_JOBS via environment variable.
> Control build threads using BUILD_JOBS env var

- dawn/src/driver-includes/arrayAddons.hpp
Fixes incorrect usage of `size_t` in `arrayAddons.hpp`
None.
Compiliation with gcc 10.1.
Was tested locally with gcc 10.1.
None
We could also include `stddef.h` instead and then `size_t` will be defined in the _global_ namespace.
> Fixed arrayAddons.hpp for gcc 10.1

- dawn/src/driver-includes/storage.hpp
For the unstructured code generation we do not use gridtools storages, nor the storage_runtime.hpp
> do not include storage_runtime if no GT

- dawn/src/dawn/SIR/SIR.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/update_dz_c.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/update_dz_c.cu
(problem discovered by Joerg Behrens)
Fixes codegen to output float/double globals in full precision (instead of default precision).
Globals d17=1.1234567890123457 and d13=1.1234567890123. Both used to get cut to 1.123457
> Fix global precision in codegen

- dawn/src/dawn/AST/Offsets.cpp
- dawn/src/dawn/AST/Offsets.h
Using #pragma once uncovered an issue in AST/Offsets.cpp. This PR fixes that and cleans up the file.
> Fix pragma once warning in AST/Offsets

- .gitignore
- dawn/scripts/_dawn4py.cpp.in
- dawn/src/dawn/Compiler/Driver.cpp
- dawn/src/dawn/Compiler/Driver.h
- dawn/src/dawn/dawn-opt.cpp
- dawn/src/dawn4py/.gitignore
- dawn/src/dawn4py/__init__.py
- dawn/test/unit-test/dawn4py-tests/test_structured.py
- dawn/test/unit-test/dawn4py-tests/test_unstructured.py
Enables us to better analyze the passes from the python command line, e.g.
```
>>> dawn4py.codegen(dawn4py.optimize(dawn4py.lower_and_optimize(sir, []), dawn4py.default_pass_groups())))
```
> Fix dawn4py bindings relating to IIR maps

- dawn/src/interface/atlas_interface.hpp
- Adds missing API to `Field` and `SparseDimension` in atlas_interface.hpp (required by cuda ico backend).
- Adds the `inline` keyword to functions which are defined in the header
> Small fixes to atlas_interface.hpp

- dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
- dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
- dawn/src/dawn/CodeGen/CXXUtil.h
- dawn/src/dawn/CodeGen/CodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
- dawn/src/dawn/CodeGen/GridTools/GTCodeGen.cpp
- dawn/src/dawn/IIR/Interval.cpp
- dawn/src/dawn/IIR/Interval.h
- dawn/src/dawn/IIR/StencilInstantiation.cpp
- gtclang/src/gtclang/Unittest/ParsingComparison.cpp
Remove usage of Support/Twine (and all helper classes) from Dawn in preparation for moving this code to GTClang.
> Remove Twine usage from dawn

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
The unstructured cuda code emitted was guarding that the number of threads is smaller then the number of entities worked on in the horizontal, but not in the vertical. This bug was masked by the fact that tests often spool up thread numbers in powers of 2, which happen to be divisible the BLOCK_SIZE. This PR fixes that issue. 
> Fix bug in unstructured Cuda Codegen

- dawn/src/dawn/CodeGen/CMakeLists.txt
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/test/integration-test/unstructured/GenerateUnstructuredStencils.cpp
- dawn/test/unit-test/dawn/CodeGen/CMakeLists.txt
- dawn/test/unit-test/dawn/CodeGen/Cuda-Ico/TestCuda-IcoCodeGen.cpp
- dawn/test/unit-test/dawn/CodeGen/Naive-Ico/TestNaive-IcoCodeGen.cpp
- dawn/test/unit-test/dawn/CodeGen/UnstructuredStencils.cpp
- dawn/test/unit-test/dawn/CodeGen/UnstructuredStencils.h
- dawn/test/unit-test/dawn/CodeGen/reference/reductions_cpp-naive-ico.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/reductions_cuda-ico.cu
Reductions which are not used in this exact fashion:
```
a = reduce(...)
```
but are part of a binary expression, e.g.
```
a = reduce(...) + b
```
lead to nonsensical code in the cuda code generation. This PR fixes this issue. Now, the Cuda code generation performs two passes per statement, first generating all reductions, saving each result to a temporary. In the second pass, this temporary is used in place of the reduction. 
```
ddt_vn_adv = ddt_vn_adv + reduce(
coeff_gradekin*z_ekinh,
Edge > Cell,
[-1.0, 1.0],
)
```
Two CodeGen tests have been added for this situation. Correct working of the fix was ensured using the icondusk-e2e repo. 
> Fix Faulty Code Generation for Reductions in Cuda Backend

- dawn/src/dawn/CodeGen/CMakeLists.txt
- dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.h
- dawn/src/dawn/CodeGen/CXXOpt/CXXOptCodeGen.cpp
- dawn/src/dawn/CodeGen/CXXOpt/CXXOptCodeGen.h
- dawn/src/dawn/CodeGen/Driver.cpp
- dawn/test/unit-test/dawn/CodeGen/CMakeLists.txt
- dawn/test/unit-test/dawn/CodeGen/Opt/TestOptCodeGen.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil_opt.cpp
This PR introduces the `CXXOptCodeGen` class that implements the `dawn:cxxopt` backend. It is implemented as a subclass of `CXXNaiveCodeGen`, but adds OpenMP parallel pragmas above parallel k-loops (i.e,. MultiStage.LoopOrder == Parallel), and SIMD pragmas over the innermost j-loops.
Resolves #1003
> Cxxopt backend

- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
Fixes two small bugs in the ico codegen
- Strips namespace names in front of math functions more reliably
- Correct scoping in generated code for if-then-else statements 
> Cuda ICO Codegen Fixes

- gtclang/CMakeLists.txt
There is a typo in setting `GTCLANG_BUILD_TESTING_GT_CUDA` and `GTCLANG_BUILD_TESTING_PLAIN_CUDA` which disables CUDA tests by default if `ENABLE_CUDA_IF_FOUND == ON`. Not sure if testing is affected (if the flags were set explicitly tests are ok).
> Fix: CUDA tests are disabled if CUDA should be enabled

- gtclang/src/gtclang/Support/Logger.cpp
Logger accidentally added the prefix e.g. WARNING twice. This fixes it.
> Fix double logger prefix

- Dockerfile
- docker/ubuntu19.10.dockerfile
- docker/ubuntu20.04.dockerfile
- docker/update-images
CMake 3.14 is required with GridTools v1.1. The GPU build image using 18.04 has at least 3.14 installed through the Kitware PPA, but Ubuntu 19.10 is not supported in the PPA. Therefore, this updates to the next LTS release, Ubuntu 20.04, for the CPU build and uses that PPA.
> Update CPU build to Ubuntu 20.04

- dawn/src/dawn/AST/ASTExpr.h
- dawn/src/dawn/AST/ASTStmt.h
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.h
- dawn/test/unit-test/dawn/Validator/TestUnstructuredDimensionChecker.cpp
There is a problem with the unstructured dimensions checker: VarDeclStmts as well as VarAccessExprs were never considered in the visitor, leaving some statements without a location type. This marked actually valid IIR as invalid.
Addresses first bullet point of [#720](https://github.com/MeteoSwiss-APN/dawn/issues/720)
New test in `TestUnstructuredDimensionsChecker`
> Fix a Bug in the Unstructured Dimensions Checker

- dawn/src/dawn/SIR/SIR.cpp
`max_digits10` guarantees no loss when serializing -> deserializing
> Unlike most mathematical operations, the conversion of a floating-point value to text and back is exact as long as at least max_digits10 were used (9 for float, 17 for double)
from https://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10
> Use max_digits10 for serialization

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.h
- dawn/src/driver-includes/cuda_utils.hpp
This PR adapts the cuda-ico codegen to accept new entry points. We now have 3 ways to launch cuda kernels
- A collection of `unstructured_interface` fields (ease of testing)
- A bunch of raw pointers on the GPU (test / launch from ICON)
- A bunch of raw pointer on the CPU (allows convenient point of entry when launching the kernel via the cpp_bindgen headers from C or C++)
Tested manually using icondusk-e2e
> CUDA Ico Backgen: Interface Changes

- dawn/src/dawn/Validator/WeightChecker.cpp
- dawn/src/dawn/Validator/WeightChecker.h
The `WeightChecker` prevented weights from being constructed that contain function calls. Even though I introduced this check, I can currently not think of a good reason to disallow such weights. Maybe I put this into place because I misunderstood what a `FunCallExpr` in dawn does. I can see no harm being done by allowing math functions in weights, the generated code looks good and no tests are failing, so I'm re-enabling such weights.
Example in dusk
```
def power_operator(
a: Field[Edge], b: Field[Edge], d: Field[Edge > Cell]
):
with levels_downward:
a = min_over(Edge > Cell, pow(d, 5), weights=[b ** 3, -1])
```
> Removed a Restriction which doesn't Allow FunCalls in Weights

- dawn/CMakeLists.txt
- dawn/cmake/HasUnstructuredDeps.cmake
- dawn/test/integration-test/CMakeLists.txt
- dawn/test/unit-test/CMakeLists.txt
Fixes recurrent problem with `HAS_UNSTRUCTURED_DEPS` cached variable (unstructured integration tests or interface unit tests not being built).
> Fix HAS_UNSTRUCTURED_DEPS

- dawn/src/dawn/IIR/DoMethod.cpp
- dawn/src/dawn/Validator/IntegrityChecker.cpp
- dawn/src/dawn/Validator/IntegrityChecker.h
Update `FieldAccessExpr::getName()` to be the correct name (found in metadata).
Adds equality check in `IntegrityChecker`.
resolves #591
> Update field access name

- dawn/src/dawn/Unittest/IIRBuilder.cpp
- dawn/src/dawn/Validator/IntegrityChecker.cpp
- dawn/src/dawn/Validator/IntegrityChecker.h
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
- dawn/test/unit-test/dawn/Validator/TestIntegrityChecker.cpp
- dawn/test/unit-test/dawn/Validator/TestUnstructuredDimensionChecker.cpp
There was an oversight in the unstructured Dimensions checker never looking at the sparse dimension of a `FieldAccessExpr` in a reduction or loop (fill) concept. Hence, this dusk code was accidentally allowed:
```
@stencil 
def ambiguous_sparse_fill_bug( 
sparse_field: Field[Edge > Vertex > Edge, K], edge: Field[Edge, K], 
): 
with levels_downward: 
with sparse[Edge > Cell > Edge]: 
sparse_field = edge[Edge > Cell > Edge] 
```
> Unstructured Dimension Checker Fix

- dawn/src/dawn/Unittest/IIRBuilder.cpp
- dawn/src/dawn/Unittest/IIRBuilder.h
- dawn/src/dawn/Validator/IntegrityChecker.cpp
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
- dawn/test/unit-test/dawn/Validator/TestIntegrityChecker.cpp
Stuff like 
```
inField: Field[Edge] #2D Field
outField: Field[Edge] #2D Field
with levels_upward:
inField = outField[k+1]
```
was legal in dawn. This PR rectifies that oversight.
fixes issue #1031
New test in `TestIntegrityChecker`
> Disallow Vertical Offsets in Horizontal Fields

- dawn/src/dawn/Optimizer/PassFixVersionedInputFields.cpp
- dawn/test/unit-test/dawn/Optimizer/TestPassFieldVersioning.cpp
This dusk code
```
@stencil
def various_expression(
edge_3d_field1: Field[Edge, K],
sparse_3d_field1: Field[Edge > Cell > Vertex > Edge, K],
):
with levels_upward:
edge_3d_field1 = min_over(Edge > Cell > Vertex > Edge, sparse_3d_field1)
with sparse[Edge > Cell > Vertex > Edge]:
sparse_3d_field1 = edge_3d_field1[Edge]
```
leads to two stages
```
sparse_3d_field1_0[<no_horizontal_offset>,0] = sparse_3d_field1[<no_horizontal_offset>,0]
```
and
```
edge_3d_field1[<no_horizontal_offset>,0] = Reduce (min, init = double_type 1.79769313486231571e+308, location = {Edge, Cell, Vertex, Edge}): sparse_3d_field1_0[<has_horizontal_offset>,0];",
for ({Edges, Cell, Vertices, Edges) {
sparse_3d_field1[<has_horizontal_offset>,0] = edge_3d_field1[<no_horizontal_offset>,0];
}
```
Which trips up the …
> Properly Version Sparse Fields

- dawn/test/integration-test/unstructured/CMakeLists.txt
- scripts/daint-test
I wasn't able to run "./scripts/daint-test" on the commit this branch is based on. Although CI approved of it.
These commits let me run "./scripts/daint-test".
Let's see what CI thinks of it.
> Improves daint-test.

- dawn/src/dawn/Support/Exception.cpp
Fixes #1055 
This
https://github.com/MeteoSwiss-APN/dawn/blob/30ba6f1e840471dc927be1774608b1649eafc251/dawn/src/dawn/Support/Exception.cpp#L41
is returning a const char* of a temporary, which leads to undefined behaviour
> fix exception

- dawn/src/dawn/CodeGen/Cuda-ico/IcoChainSizes.cpp
Missing include to `stdexcept` in IcoChainSizes.cpp making gcc 10.2 fail to compile.
Thanks to @JoergBehrens for reporting this.
> Fix include in IcoChainSizes.cpp

- dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.h
During the workshop a problem w.r.t to dense indices in reductions was noticed, quite possibly introduced by [this refactoring](https://github.com/MeteoSwiss-APN/dawn/commit/35209afd9942e7cefd6915c03b0335f82897e70d)
`grad_of_curl = sum_over(Edge > Vertex, uv_curl*tangent_orientation, weights=[-1., 1, ])/L`
vs
`grad_of_curl = sum_over(Edge > Vertex, uv_curl, weights=[-1., 1, ])/L*tangent_orientation`
both of these stencils should be equal. however, the first version tried to access `tangent_orientation` with `red_loc`, which is the vertex index (while `tangent_orientation` lives on edges).
Currently the fix is not tested, need to act fast because of the ongoing workshop
> Hot Fix for the Ongoing Workshop (Dense Indexing)

- Dockerfile
We rely quite a bit on assertions for error handling in dawn. This breaks apart if dawn is used in the release build. For the workshop, we rely on error messages being generated in order to not confuse the students. This can be rolled back after the workshop
> Set Dockerfile to Debug Build

- Dockerfile
- dawn/src/dawn/Optimizer/PassValidation.cpp
Exceptions give nicer error messages in Jupyter Notebooks and, as opposed to assertions, also work in dawns Release mode. The error handling in dawn needs an overhaul either way. I don't know if bubbling up an exception is the proper way to go, however, it does seem more reasonable in instances for syntax errors and the like. Hence, all assertions in the validation pass were replaced by throwing semantic exceptions. This could serve as a stepping stone to further improve dawn's error handling.
> Throw Instead of Assert in PassValidation

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
The Cuda ICO backend assumed that every API field is also a stencil field. It did this while trying to figure out which fields are being written to in order to not clutter the functions copying fields back to the host. This is now fixed.
Fixes #1068 
Examples like:
```
@stencil
def vert_offset_write(
a: Field[Edge,K], b: Field[Edge,K], unused: Field[Edge, K]):
with levels_downward as k:
a = b
```
should not break at cuda code gen time anymore.
Unfortunately can not be tested in dawn because we do not support compiling of generated cuda code in the current testing. Manually tested in icondusk-e2e.
> Cuda-ICO Backend Assumed that every API Field is a Stencil Field

- dawn/src/driver-includes/math.hpp
Implements the math functions defined to be "standard" in gt4py land, c.f. [here](https://github.com/GridTools/gt4py/blob/ceb2b02669f9cc535a7d0d48e3810cc85d6a8e4d/src/gt4py/backend/gt_backends.py#L184). 
Fixes #1072 
Fixes #1073 
Tested manually using dusk
> Implement gt4py Math Standard

- dawn/src/dawn/SIR/SIR.cpp
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
- dawn/src/dawn/Validator/UnstructuredDimensionChecker.h
- dawn/src/dawn4py/_dawn4py.cpp
- dawn/test/integration-test/unstructured/AtlasIntegrationTestCompareOutput.cpp
- dawn/test/unit-test/dawn/Optimizer/TestPassLocalVarType.cpp
- dawn/test/unit-test/dawn/Validator/TestUnstructuredDimensionChecker.cpp
So far we failed to ensure location type consistency in between the conditional, then and else branch of of an `IfStmt`. This allowed code like:
```
@stencil
def if_condition(hC_x: Field[Cell],
boundary_edges: Field[Edge]):
with levels_downward:
if boundary_edges:
hC_x = 0
```
To go through the pipeline, being generated into potentially unsafe code. 
Fixes #1064 
See above
Death- and positive tests added to `TestUnstructuredDimensionsChecker` with simple as well as nested if statements 
> Ensure Location Type Consistency in IfStmt

- dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
- dawn/test/integration-test/dawn4py-tests/data/ICON_laplacian_stencil_ref.cpp
- dawn/test/integration-test/unstructured/AtlasIntegrationTestCompareOutput.cpp
- dawn/test/integration-test/unstructured/CMakeLists.txt
- dawn/test/integration-test/unstructured/GenerateUnstructuredStencils.cpp
In the naive backend, each reduction was wrapped into its own scope. This caused some problems in if statements where a reduction was part of the condition, as well as situations where a temporary field was demoted to a local variable. This PR addresses this by removing the scope. The local linear index is now introduced in the lambda capture, which is made possible by marking the lambda as `mutable`. 
Fixes #1065 
A real life example could be
```
with levels_downward:
if sum_over(Cell > Edge, 1) < 4:
f_x = ... #do something at the boundary
else:
f_x = sum_over(Cell > Edge, L)
```
A test to the effect of the above was added to the unstructured integration checking. 
> Fix Scoping Issues In Naive Codegen

- dawn/src/dawn/Validator/IndirectionChecker.cpp
- dawn/src/dawn/Validator/IntegrityChecker.cpp
- dawn/test/unit-test/dawn/Validator/TestIndirectionChecker.cpp
- dawn/test/unit-test/dawn/Validator/TestIntegrityChecker.cpp
* A (1) vertically offset _write_ test case exists in the clang-gridtools tests. `gt4py` is set to support it, reasoning that there may be valid use cases. Long term goal there seems to be to support arbitrary computations along the vertical (even double loops etc.)
* Note 07.12.2020: Rechecked the part of the ICON dycore we are set to translate. Vertically offset writes **NO NOT** appear!
* Note 10.12.2020: We decided to **not** support vertically offset writes for now. 
So far, writes using a vertical indirections (i.e. using an `IndexField`)  were correctly prohibited, but writes using a compile time offset in the vertical only were accidentally allowed. This caused code like 
```
@stencil
def vert_offset_write(
outF: Field[Edge,K], inF: Field[Edge,K]):
with levels_downward as k: …
```
> Prohibit Vertically Offset Writes

- dawn/src/dawn/Optimizer/PassStageMerger.cpp
- dawn/test/unit-test/dawn/Optimizer/TestPassStageMerger.cpp
- dawn/test/unit-test/dawn/Optimizer/input/StageMergerTestDependent.iir
- dawn/test/unit-test/dawn/Optimizer/input/StageMergerTestIndependent.iir
- dawn/test/unit-test/dawn/Optimizer/samples/StageMergerIndependent.py
- dawn/test/unit-test/dawn/Optimizer/samples/StagemergerDependent.py
When the stage merger encountered a candidate stage not on the same location as the current stage, it would simply proceed to the next stage further above. However, this is only legal if the stage to be skipped is independent of the current stage. 
Fixes #1053
Consider this Example
```
eout0 = sum_over(Edge > Cell > Edge, ein0[Edge > Cell > Edge])
cout0 = sum_over(Cell > Edge > Cell, cin0[Cell > Edge > Cell])
eout1 = sum_over(Edge > Cell, cout0)
```
here, `eout1` depends on `cout0`. We are thus not allowed to merge the last stage into the very first 
Consider on the other hand:
```
eout0 = sum_over(Edge > Cell > Edge, ein0[Edge > Cell > Edge])
cout0 = sum_over(Cell > Edge > Cell, cin0[Cell > Edge > Cell])
eout1 = sum_over(Edge > Cell > Edge, ein1[Edge > Cell > Edge]) 
```
here, the stage …
> Fix a Stage Merger Problem on Unstructured Stencils 

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/SIR/SIR.cpp
- dawn/src/dawn/SIR/SIR.h
As the title says, before it was not counting the sparse dimension. Rank computation moved inside `FieldDimensions`.
Testing through icondusk-e2e PR: https://github.com/dawn-ico/icondusk-e2e/pull/34
> Fix rank calculation in F90 interface generator

- dawn/src/interface/atlas_interface.hpp
This PR fixes a bug in the unstructured interface where the center element (if included) could reside in any position in the returned neighbor list. However, we rely on the fact that this is always returned first (also in ICON).
Tested in `icondusk-e2e`
> Make Neighbor Lists Including Center Contain Center First

- dawn/src/dawn/AST/ASTExpr.h
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.h
- dawn/src/dawn/CodeGen/F90Util.h
- dawn/test/integration-test/unstructured/GenerateUnstructuredStencils.cpp
Currently, temporary fields are allocated in the constructor of the generated class. Since the API functions to the FORTRAN and cpp drivers hold the stencil on the stack, this leads to memory (de-)allocation on each call. This is fine for debugging, but not for production runs. Thus, this PR keeps that behavior for the convenience wrappers starting from host memory, but introduces static `setup` and `free` functions which have to be called by the host when using the production interface which assumes device pointers. 
Additionally, since the APIs are touched either way, globals can now be communicated from FORTRAN to the CUDA backend. 
Furthermore this PR contains a small refactoring and removes the (now) superfluous template parameter from the generated stencil class
Addresses part of …
> Introduce Persistent Temporary Fields and Mesh to the Cuda Backend

- dawn/src/dawn/AST/ASTExpr.cpp
- dawn/src/dawn/AST/ASTExpr.h
- dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
Fixes the bugs in the following two tasks:
Fixes #1097 : Now explicitly check if the `lowerLevel` and `upperLevel` of the interval are both `End`.
Fixes #1098 : Now branch with `sum_over` being the special case and `max_over`, `min_over` behaving the same way.
> Fixed two bugs in codegen, one related to intervals, one to max_over (#1097 and #1098)

- dawn/src/dawn/CodeGen/CMakeLists.txt
- dawn/src/dawn/CodeGen/Driver.cpp
- dawn/src/dawn/Support/ClangCompat/CompilerInvocation.h
- dawn/src/dawn/Support/ClangCompat/EvalResult.h
- dawn/src/dawn/Support/ClangCompat/FileSystem.h
- dawn/src/dawn/Support/ClangCompat/FileUtil.h
- dawn/src/dawn/Support/ClangCompat/ImplicitNodes.h
- dawn/src/dawn/Support/ClangCompat/SourceLocation.h
- dawn/src/dawn/Support/ClangCompat/VirtualFileSystem.h
- dawn/test/integration-test/dawn4py-tests/data/ICON_laplacian_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/copy_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/generate_versioned_field_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/hori_diff_stencil_ref.cpp
- dawn/test/integration-test/dawn4py-tests/data/tridiagonal_solve_stencil_ref.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cu
- dawn/test/unit-test/dawn/CodeGen/reference/global_indexing.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/global_indexing.cu
- dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil.cu
- dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil_nosync.cu
- dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil_opt.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/nonoverlapping_stencil.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/nonoverlapping_stencil.cu
- dawn/test/unit-test/dawn/CodeGen/reference/update_dz_c.cpp
- dawn/test/unit-test/dawn/CodeGen/reference/update_dz_c.cu
The formatting style for the generated code:
```
clang::format::FormatStyle style =
clang::format::getLLVMStyle(clang::format::FormatStyle::LanguageKind::LK_Cpp);
style.PointerAlignment = clang::format::FormatStyle::PAS_Left;
style.ColumnLimit = 100;
style.SpaceBeforeParens = clang::format::FormatStyle::SBPO_Never;
style.AlwaysBreakTemplateDeclarations = clang::format::FormatStyle::BTDS_Yes;
```
is chosen so that it reflects the formatting style in the dawn project:
```
BasedOnStyle:                                           LLVM
ColumnLimit:                                            100
PointerAlignment:                                       Left
SpaceBeforeParens:                                      Never
AlwaysBreakTemplateDeclarations:                        true
```
Dawn now …
> Generated code now formatted with clang::libFormat

- dawn/src/driver-includes/bindings/dawn_utils.f90
- dawn/src/driver-includes/cuda_utils.hpp
Ship with dawn the API to set markers' indices (and its binding). Also add missing bindings to serialization utilities (so that can be used in any place within the model code).
> Add set_splitter_index and some bindings

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/driver-includes/bindings/dawn_utils.f90
- dawn/src/driver-includes/cuda_utils.cpp
- dawn/src/driver-includes/cuda_utils.hpp
There is not necessarily a relation between the upper and lower indices as retrieved from the `get_indices_(e|c|v)` call. I.e. for
```
CALL get_indices_e(p_patch(jg), 1, 1, 1, edge_start_idx_a, edge_end_idx_b, a, b)
CALL get_indices_e(p_patch(jg), 1, 1, 1, edge_start_idx_b_prime, edge_end_idx_c, b, c)
```
it neither holds that `edge_end_idx_b == edge_end_idx_b_prime` nor |edge_end_idx_b - edge_end_idx_b_prime| == 1`. 
Consequently, we need to also distinguish between upper and lower indices in dawn to avoid awkward workarounds if a index is used as lower and upper index by two different stencils. This PR splits the single subdomain structure into a upper and lower one, both holding a map for subdomain markers.
Tested in `ICON-DSL`
> Divide Upper and Lower Index for Subdomains

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/driver-includes/to_vtk.cpp
- dawn/src/driver-includes/to_vtk.h
The serialization routines had some problems:
* Calling the destructor the second time a serialization routine is called is not safe. A single stencil may serialize multiple fields in the same iteration
* The use of `rdbuf` caused some problems. See also this [stackoverflow question](https://stackoverflow.com/questions/324711/writing-stringstream-contents-into-ofstream) (later answers)
Tested using ICON-DSL
No dependencies
> Fix Serialization 

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
Switch from ternary pattern to if/else when evaluating the optional threshold argument (details: https://github.com/j3-fortran/fortran_proposals/issues/138#issuecomment-573322935 ). Fixes the access to uninitialized memory problem.
Manually tested in the integration with ICON
> Fix optional threshold

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
It sets cuda block size in K to 1. That means all cuda threads of different levels fall into different cuda blocks. 
The reason for this is to optimize the resources when Ksize != Y x BLOCKSIZE. 
There were two arguments in favor of blocking cuda threads in the vertical: 
* input field accesses at displace k offset could be found in cache if contiguous threads in the vertical compute in the same SM. 
* lookup tables can also be cached and reused among multiple k levels. 
The same effect for cache behaviour is achieved using LEVELS_PER_THREAD. However overall the best value of LEVELS_PER_THREAD is 1. 
See columns C & G
https://docs.google.com/spreadsheets/d/1w2mkdWLVXPOrvufPAwRRhscuT--37qf3o2uhZKG7tqU/edit#gid=730428313
> block size 1 for K dimension

- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
ICON treats pentagons by setting the value of the connectivity to 0 for the non existing (last) grid point. 
https://gitlab.dkrz.de/dsl/icon-cscs/-/blob/master/src/shr_horizontal/mo_model_domimp_patches.f90#L2066
When translating the lookup tables to C++, this value becomes -1. 
In the cuda kernels, we skip execution of this points with a conditional: 
```
if (nbhIdx == DEVICE_MISSING_VALUE) { continue; }
```
However, this introduces a significant performance penalty in some kernels, i.e. stencil_05.
In this PR, we only code generate this conditional when needed for pentagons: 
if there is a vertex in the location chain, that is not last location. 
For example,
E->C->V will not require code generation of the conditional
E->V->C will require code generation of the conditional
E-> V will …
> Remove conditional for missing value on pentagons

- dawn/src/driver-includes/to_vtk.cpp
- dawn/src/driver-includes/to_vtk.h
Necessary for multi-node output: each mpi work rank in ICON would write independently to its own file.
Example:
```
mo_nh_diffusion_stencil_19_rank0_theta_v_0.csv
mo_nh_diffusion_stencil_19_rank1_theta_v_0.csv
```
Works also with 1 work rank (current setup), the `rank0_` part would be added in any case.
It doesn't necessarily require the code (on the model side) to set the rank ID, if only one work rank is used (as there's a default of 0).
In `icon-dsl`.
> Add rank ID to serialized vtk/csv filenames

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/driver-includes/cuda_utils.cpp
- dawn/src/driver-includes/cuda_verify.cpp
- dawn/src/driver-includes/cuda_verify.hpp
Now use `numpy.isclose`-inspired verification method using the following formula:
```
abs(dsl[pidx] - fortran[pidx]) <= (abs_tol + rel_tol * abs(fortran[pidx]))
```
The user now can also provide `abs_tol` and `rel_tol` per OUT/INOUT field and not per kernel. There are default values in place for `abs_tol=0.0` and `rel_tol=1e-12`.
If verification fails, more information about the dsl and reference fields is given now: min, max, average.
The relative error formula below could lead to false positives in verification failure:
```
double error = 0.;
if(expected == actual) {
} else if(fabs(expected) < 1e-6 && fabs(actual) < 1e-6) {
error = fabs(expected - actual);
} else {
error = fabs((expected - actual) / expected);
}
```
This is no longer in dawn.
> Use numpy isclose-like verification, allow per field tolerances

- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.h
- dawn/src/dawn/CodeGen/Options.inc
- dawn/src/dawn4py/_dawn4py.cpp
In `icondusk-e2e` we test on atlas meshes on the full domain. This means that neighborhood entries may be missing even without the pentagon / hexagon issue (at the border). This PR introduces a switch to emit a guard against such neighborhoods for _all_ chains. 
`./dawn-codegen --atlas-compatible test_reduce.iir -b cuda-ico -o out.cpp`
Tested using `icon-dusk` 
> Add switch for Atlas Compatibility

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.h
- dawn/src/dawn/CodeGen/Options.inc
Levels per thread and block size were hardcoded based an preliminary tests on daint. Tests on tsa have shown that these values need to be tuneable per stencil (i.e. there is no "global" optimum). This PR introduces the possibility to specify these parameters using command line args to `dawn-codegen`
```
./dawn-codegen --levels-per-thread=42 --block-size=1337 test_reduce.iir -b cuda-ico -o out.cpp && code out.cpp
```
Tested manually
> Make Block Size and Levels per Thread an Option to Codegen

- dawn/src/driver-includes/to_vtk.cpp
Serializing double precision fields to vtk was lossy due to a number of factors. This and related issues are fixed here:
- Changed vtk data types from `float` to `double`.
- Added `setprecision` to vtk functions
- Fixed `formatNaN` to respect `setprecision` (for more see below)
- Fixed types and `max_digits10` for `setprecision` (for more see below)
I considered various different options. Before, the function `formatNaNs` returned a string and the function didn't respect `setprecision`. I wanted that `formatNaNs` respects `setprecision` while also formating NaNs correctly (as `"nan"`). I could have also used a string stream and then set the precision each time before formatting the double into that string stream. However, this means the function won't respect `setprecision` of other …
> Vtk precision fixes

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
It fixes a bug where broken code gets generated if an API field is unused.
The code generated wrapper function will only pass used API fields to the run call.
If an API field is unused, it will occur in the signature of the run function, but it will be missing when the function is called in the wrapper function. Thus the call is invalid and the generated code is broken.
Tested manually with ICON.
> Unused api fields bugfix

- dawn/src/interface/atlas_interface.hpp
Joerg Behrens reported the following:
in the file `dawn/src/interface/atlas_interface.hpp` you define the class
`SparseDimension`. There, the access `operator()` seems to expect the
following order of dimensions `(elem_dim, sparse_dim, level_dim)`, e.g.:
```
T const& operator()(int elem_idx, int sparse_dim_idx, int level)
```
The `getShape()` method, however, returns the field shape in the class
internal order of dimensions which seems to be (elem_dim, level_dim,
sparse_dim).
Therefore the field shape given by `getShape()` seems to be inconsistent
with the field access or, in other words: The shape does not give the
access bounds of the access operator as would be expected (I am only
guessing the semantics from the method name - which triggers my Fortran
background).
In my opinion a …
> Make getShape convenience method in atlas_interface consistent

- dawn/src/dawn/IIR/StencilMetaInformation.h
- dawn/src/dawn/Validator/IntegrityChecker.cpp
- dawn/src/dawn/Validator/IntegrityChecker.h
During the stencil integration a bug in the dawn integrity checking was noticed with situations of the form:
```
@stencil
def test_stencil(
levelmask: Field[K],    b: Field[Edge, K]       
) -> None:
a: Field[Edge, K]
with domain.upward as k:
a = 0.0
if (levelmask[k]):
a = b   
```
This (valid) code was rejected by dawn if `--default-opt` was set. In the issue it was theorized that the `levelmask` is to blame, since the error message read " trying to assign verticald field to fulld field!". This turned out not to be true; the error was in fact a missing visitor looking at `VarAccessExpr`. If `--default-opt` is set, the field `a` is demoted to a local scalar variable. Since there was no visitor for this variable, the `IntegrityChecker` was indeed comparing the dimensions of `levelmask` and …
> Add VarAccessExpr to Integrity Checking

- dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
Consider [this PR](https://github.com/MeteoSwiss-APN/dawn/commit/91a9bde561881c2408032347c08179718426be58), i.e. introducing a `kSize` per output field in order to be able to merge stencils on different vertical domains. This has some problems, because `k` is not only used as an iterator variable, but also as stride in the case of "full" sparse fields. As a simple fix to this problem, this PR switches the full sparse field layout to: `[numlev, sparse_size, dense]`. 
Old addressing:
```
sparse_full[nbhIter0 * kSize * CellStride + (kIter + 0) * CellStride + pidx]
```
becomes a problem if the stencil has domain `kSize + 1` but field `sparse_full` is only allcoated for `kSize` levels. Switching the layout to:
```
vcoef[(kIter + 0) * C_E_C_SIZE * CellStride + nbhIter0 * CellStride + pidx]
``` …
> Swap Dimensions on Sprase Full Fields

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/driver-includes/cuda_verify.cpp
- dawn/src/driver-includes/cuda_verify.hpp
The verification functions in our `cuda_verify` files did not respect the stream being set in the setup function of the stencil. This was safe since the verification functions call a `cudaDeviceSynchronize()` (both explicitly as well as implicitly using `cudaMalloc`). However, it is still good practice to run everything in the stream that the user set.
> Make Verification Functions Run in Same Stream as Kernel

- docker/dawn-env.dockerfile
- scripts/daint-test
the dawn jenkins plan (and the corresponding script) did the following, which worked on `daint` until June 6th:
```
sarus pull image
srun sarus run image
```
But since the `daint` update one needs to do the `sarus pull` with `srun` on a compute node:
```
srun sarus pull image
srun sarus run image
```
Otherwise the image cannot access the internet.
The small changes to `docker/dawn-env.dockerfile` are due to cmake not accepting the `--` arguments anymore. This resulted in errors when building new docker images.
> Use `srun ... sarus pul image` instead of `sarus pull image` so the container has rights to access the internet

- dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
- dawn/src/driver-includes/cuda_utils.hpp
- dawn/src/driver-includes/to_json.cpp
- dawn/src/driver-includes/to_json.hpp
* For multiple nodes multiple verification files are created. Each process writes into a separate file. All stencils get handed a pointer to a shared object at setup time. At the end of an ICON run that object gets dumped into a file.
* Nproma is no longer hard coded but passed to the stencils during setup time. Specifically `Nproma` is now part of the `GlobalGpuTriMesh` struct.
> Fixed multinode verification, fixed hardcoded nproma
