MeteoSwiss-APN/dawn

.travis.yml
CMakeLists.txt
cmake/AddProtobuf.cmake
cmake/CMakeLists.txt
cmake/DawnCMakeInit.cmake
cmake/DawnMacros.cmake
cmake/modules/DawnAddExecutable.cmake
cmake/templates/DawnConfig.cmake.in
scripts/travis/driver-test.sh
scripts/travis/install.sh
scripts/travis/install_protobuf.sh
src/dawn/CMakeLists.txt
test/unit-test/dawn/CMakeLists.txt

Add support for Protobuf

---

src/dawn/CodeGen/ASTCodeGenGTClangStencilBody.cpp

Update code generation to reflect gridtools changes

---

cmake/DawnDefinitions.cmake

- Fix retrieval of git hash to be more robust

Fix retrieval of git hash in cmake

---

scripts/jenkins/build.sh

Description
===========
adapt kesch environment after the upgrade of kesch TDS

fix kesch env

---

src/dawn/IIR/DoMethod.cpp
src/dawn/IIR/DoMethod.h
src/dawn/IIR/Field.cpp
src/dawn/IIR/IIRNode.h
src/dawn/IIR/MultiStage.cpp
src/dawn/IIR/MultiStage.h
src/dawn/IIR/Stage.cpp
src/dawn/IIR/Stage.h
src/dawn/IIR/Stencil.cpp
src/dawn/IIR/Stencil.h
src/dawn/IIR/StencilFunctionInstantiation.cpp
src/dawn/IIR/StencilInstantiation.cpp
src/dawn/Optimizer/PassFieldVersioning.cpp
src/dawn/Optimizer/PassInlining.cpp
src/dawn/Optimizer/PassSetNonTempCaches.cpp
src/dawn/Optimizer/PassStageMerger.cpp
src/dawn/Optimizer/PassTemporaryToStencilFunction.cpp

* Add and compute a field derived info at the DoMethod level. 
* Fix in the up propagation of the derived info

fields at the level of DoMethod

---

src/dawn/Compiler/DawnCompiler.cpp

Minor fix to not assert on illegal backend but to exit properly

fix return on bad backend

---

src/dawn/IIR/StencilInstantiation.cpp
src/dawn/Optimizer/OptimizerContext.h

coming from unresoved issues in 172 that were overlooked

implementation of the two missing comments

---

src/dawn/IIR/DoMethod.cpp
src/dawn/IIR/Field.cpp
src/dawn/IIR/MultiStage.cpp
src/dawn/IIR/Stage.cpp
src/dawn/IIR/Stencil.cpp

This is a bugfix as described in #180.

fix ordering problem of fields described in #180

---

scripts/jenkins/build.sh

Creates an option to install dawn in a specific place in the jenkins env

update jenkins script

---

src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
src/dawn/Support/IndexRange.h

Only create views for data stores that are actually needed

---

CMakeLists.txt

Change it back to what it was before
Decides what the default build type should be

fix build type

---

gtclang/scripts/jenkins/submit.daint.slurm

Should improve scheduling time on daint.

Switch to cscsci queue

---

dawn/bundle/PostInstall.cmake

`PostInstall.cmake` should also check the return value of the process that runs the python script.
Relates #324

Check return value in PostInstall

---

dawn/bundle/PostInstall.cmake
dawn/src/dawn/IIR/DoMethod.cpp
dawn/src/dawn/IIR/StencilMetaInformation.cpp
dawn/src/dawn/IIR/StencilMetaInformation.h

Fixes the unstructured python example by adding a default unstructured field-type 
Broken python example
Fixes https://github.com/MeteoSwiss-APN/dawn/issues/324
This PR is built on top of https://github.com/MeteoSwiss-APN/dawn/pull/325

Fix python test

---

gtclang/src/gtclang/Driver/CompilerInstance.cpp
gtclang/src/gtclang/Support/ClangCompat/CompilerInvocation.h
gtclang/src/gtclang/Support/ClangCompat/EvalResult.h
gtclang/src/gtclang/Support/ClangCompat/FileSystem.h
gtclang/src/gtclang/Support/ClangCompat/FileUtil.h
gtclang/src/gtclang/Support/ClangCompat/ImplicitNodes.h
gtclang/src/gtclang/Support/ClangCompat/SourceLocation.h
gtclang/src/gtclang/Support/ClangCompat/VirtualFileSystem.h
gtclang/src/gtclang/Support/FileUtil.cpp

Fixes some API changes in clang 10 (master branch as of Oct 14 2019).

Support for clang 10 aka master

---

dawn/bundle/CMakeLists.txt
gtclang/bundle/CMakeLists.txt

Fix yoda version with infinite recursion in dawn bundle.

Fix infinite recursion in dawn bundle build

---

dawn/scripts/jenkins/build.sh
dawn/src/dawn/Compiler/CMakeLists.txt

Looks like this fixes #323 (replacement for #337).

Really fix the CMake race condition on protobuf

---

README.md

Add a ZenHub badge and link to the README
Fixes #430 
Tested the md of the branch and the corresponding links

Add zenhub to readme

---

dawn/prototype/atlas_interface.hpp

Quick PR that extends the ATLAS interface to include the reductions which were missing. 
Currently not tested. To be tested along with the naive atlas codegen

extended atlas interface to include all possible reductions

---

dawn/scripts/jenkins/env_daint.sh
gtclang/scripts/jenkins/env_daint.sh

Daint: cuda 10.1 after upgrade

---

dawn/src/dawn/IIR/Extents.h
dawn/src/dawn/Optimizer/PassSetBlockSize.cpp
dawn/src/dawn/Support/ArrayRef.h

Another dangling reference was introduced. Caught by clang-tidy.

Fix dangling reference

---

dawn/scripts/jenkins/env_daint.sh
gtclang/scripts/jenkins/env_daint.sh

Describe here what the PR does
Put the link to the issue here
(e.g resolves #XXX)
If a specific example is being fixed, put it here
If anything besides a simple launch needed (perf-test), link it here
If this is built on top of anything else, put it here

Try new clang installation

---

dawn/src/dawn/Optimizer/PassSetStageGraph.cpp

Changes the dependency analysis in PassSetStageGraph to detect WAW.
Resolves  #477.

Catch WAW dependency

---

dawn/src/dawn/CodeGen/CXXNaive/ASTStencilDesc.cpp
dawn/src/dawn/CodeGen/CXXNaive/CXXNaiveCodeGen.cpp
dawn/src/dawn/CodeGen/CXXUtil.h
dawn/src/dawn/IIR/Stage.cpp
dawn/src/dawn/IIR/Stage.h
dawn/src/dawn/IIR/StencilInstantiation.cpp
dawn/src/dawn/Optimizer/OptimizerContext.cpp
dawn/src/dawn/Optimizer/PassStageMerger.cpp
dawn/src/dawn/Unittest/IIRBuilder.h
dawn/src/driver-includes/verify.hpp
dawn/test/unit-test/dawn-c/TestCompiler.cpp

Implementation of code-generation for globally indexed stages
Fixes #492

IIR / Codegen for global indexing

---

dawn/src/dawn/AST/ASTExpr.h

Document the expected behaviour of stencil functions in dawn
#416

document behaviour of stencil functions

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/IIR/DependencyGraph.h
dawn/src/dawn/IIR/Stencil.cpp
dawn/src/dawn/Optimizer/OptimizerContext.cpp
dawn/src/dawn/Optimizer/PassMultiStageSplitter.cpp
dawn/src/dawn/Optimizer/PassStageReordering.h
dawn/src/dawn/Optimizer/PassTemporaryMerger.cpp
dawn/src/dawn/Optimizer/ReorderStrategyGreedy.cpp

Fixes some typos
Enhances comments

fix some typos

---

dawn/examples/tutorial/README.md
dawn/examples/tutorial/laplacian_stencil.py

Fixes the tutorial with the new python usage

fix tutorial with new python

---

dawn/src/dawn/Compiler/DawnCompiler.cpp

No change in code behavior. Simply writing C++ code and conforming to naming rules.

Conform to naming guidelines and write better code

---

dawn/setup.py
dawn/src/dawn4py/serialization/utils.py

Fixes the python installation
Broken master with disabled tests
See gt4py2dawn

Fix python install

---

dawn/setup.py
dawn/src/dawn4py/CMakeLists.txt

Changes to setup.py in support of pip install.
Resolves #580.

Dawn changes to setup.py

---

gtclang/test/integration-test/tester.py

Fix bug I introduced when writing tester.py.

Fix tester.py

---

dawn/src/dawn/IIR/CMakeLists.txt
dawn/src/dawn/SIR/CMakeLists.txt

Fix the copy target for generated python proto files.

Fix python proto copy target

---

dawn/src/dawn/IIR/CMakeLists.txt
dawn/src/dawn/SIR/CMakeLists.txt

Use add_custom_target + add_custom_command

---

dawn/src/dawn/IIR/CMakeLists.txt
dawn/src/dawn/SIR/CMakeLists.txt

Reverts MeteoSwiss-APN/dawn#627

Revert "Use add_custom_target + add_custom_command"

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Optimizer/OptimizerOptions.inc
gtclang/src/gtclang/Driver/Driver.cpp
gtclang/src/gtclang/Frontend/GTClangASTConsumer.h

Add options to turn on individual passes, which can be enabled after passing `-default-none`.
Resolves #561.

Optimizer pass options

---

dawn/examples/python/run.sh
dawn/src/dawn/Serialization/SIRSerializer.cpp

Fix deserialization of SIR::field
Resolves #646

Fix deserialization of SIR::field

---

dawn/examples/python/run.sh
dawn/src/dawn/Serialization/SIRSerializer.cpp
dawn/test/unit-test/test_dawn4py/test_unstructured.py

Forgot to re-enable the python tests in `dawn/test/unit-test/test_dawn4py`

Reenable python test

---

scripts/jenkins/build_clang_gridtools.sh
scripts/jenkins/dawn_PR.sh
scripts/jenkins/srun_dawn_PR.sh

reenable daily performance tests 
https://github.com/meteoswiss-apn/dawn/issues/581
See test here: 
http://jenkins-mch.cscs.ch/view/PASCHA/job/dawn_gtclang_clang-gridtools_PR/176/
This PR is built together with https://github.com/MeteoSwiss-APN/clang-gridtools/pull/148

enable performance tests

---

gtclang/src/gtclang/Frontend/GTClangIncludeChecker.cpp
gtclang/src/gtclang/Frontend/GTClangIncludeChecker.h

- use compatibility header for filesystem
- move includes from header to source

Use compatibility header for filesystem

---

dawn/src/dawn/CodeGen/CodeGen.cpp
dawn/src/dawn/CodeGen/CodeGen.h
dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Compiler/DawnCompiler.h
dawn/src/dawn/IIR/LocalVariable.h
dawn/src/dawn/Optimizer/OptimizerContext.cpp
dawn/src/dawn/Optimizer/OptimizerContext.h
dawn/src/dawn/Optimizer/PassComputeStageExtents.cpp
dawn/src/dawn/Optimizer/PassFixVersionedInputFields.cpp
dawn/src/dawn/Optimizer/PassPrintStencilGraph.cpp
dawn/src/dawn/Optimizer/PassSetBlockSize.cpp
dawn/src/dawn/Optimizer/PassSetNonTempCaches.cpp
dawn/src/dawn/Optimizer/PassStageMerger.cpp
dawn/test/unit-test/dawn/CodeGen/Cuda/CMakeLists.txt
dawn/test/unit-test/dawn/IIR/TestIIRSerializer.cpp
dawn/test/unit-test/dawn/Optimizer/Passes/TestPassSetBoundaryCondition.cpp
gtclang/src/gtclang/Driver/Driver.cpp

Miscellaneous enhancements from `optimizer_refactor` branch that will make the merge easier. These changes are orthogonal to the larger refactor in `Compiler` and `Optimizer`.

Misc changes from optimizer_refactor

---

gtclang/src/gtclang/Frontend/GTClangASTConsumer.cpp

Output SIR to current working directory inside gtclang when using the `-write-sir` flag.

Fix SIR output path

---

dawn/src/dawn/Compiler/DawnCompiler.cpp

Clean up diagnostics on what is reported when code generation is throwing 
Currently if iteration spaces are present in the GT backend we get a useless error message. It cleans that up

clean diagnostics

---

dawn/src/dawn4py/.gitignore

Ignore version.txt in dawn4py

---

gtclang/src/gtclang/Frontend/GTClangPreprocessorAction.cpp
gtclang/test/unit-test/Frontend/TestPreprocessing.cpp
gtclang/test/unit-test/Frontend/input/test_iteration_space.cpp

Fix my original changes to the parsing for the iteration_space, and add tests to catch problems next time.

Fix iteration_space

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Compiler/Options.inc
dawn/src/dawn/Optimizer/OptimizerOptions.inc
dawn/src/dawn/Optimizer/PassSetBlockSize.cpp
dawn/src/dawn4py/_dawn4py.cpp

Rename block_size and domain_size

---

dawn/src/dawn/Optimizer/PassRemoveScalars.cpp
dawn/src/dawn/Support/Logging.cpp
dawn/src/dawn/Support/Logging.h
dawn/test/unit-test/dawn/Optimizer/Passes/TestPassRemoveScalars.cpp

Switch warning to info in PassRemoveScalars.

PassRemoveScalars: switch warning to info

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Optimizer/PassInlining.cpp
dawn/src/dawn/Optimizer/PassInlining.h
dawn/src/dawn/Unittest/CompilerUtil.cpp

Put back pass groups that were incorrectly merged.
Fixes merge in #792.

Fix optimizer merge

---

Dockerfile

Update Dockerfile environment image.
Passed!
https://hub.docker.com/repository/registry-1.docker.io/gtclang/dawn/builds/935d837d-9a5c-46ab-98f9-fd7c0f1f56a7

Update Dockerfile env image

---

dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
dawn/test/integration-test/unstructured/reference/reference_diffusion.hpp
dawn/test/integration-test/unstructured/reference/reference_gradient.hpp

remove trailing ;

---

dawn/src/dawn/Serialization/SIRSerializer.cpp
dawn/src/dawn4py/serialization/utils.py

Typo in utils.py and missing global float deserialization. Thanks to Joerg Behrens for the feedback!

Small fix utils.py and deserialization

---

dawn/test/integration-test/unstructured/CMakeLists.txt

Use gtest_discover_tests for atlas

---

dawn/src/dawn/Serialization/IIRSerializer.cpp
dawn/src/dawn/Unittest/CompilerUtil.cpp
dawn/test/unit-test/dawn/CodeGen/CMakeLists.txt
dawn/test/unit-test/dawn/CodeGen/Cuda/TestCodeGenCuda.cpp
dawn/test/unit-test/dawn/CodeGen/Naive/TestCodeGenNaive.cpp
dawn/test/unit-test/dawn/CodeGen/TestCodeGen.h
dawn/test/unit-test/dawn/CodeGen/input/conditional_stencil.iir
dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cpp
dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cu

This PR resolves the bug in the IIRSerializer class that caused global variables to be improperly serialized.
Resolves #724

Fix globals serialization

---

dawn/test/integration-test/dawn4py-tests/data/ICON_laplacian_stencil_ref.cpp

Update the reference to reflect new dawn4py

update the ref to reflect new dawn4py

---

dawn/src/dawn4py/serialization/utils.py

Left a debug print in the python interface while working on it. This PR removes that noise.

fixed unnecessary debug output

---

dawn/src/dawn4py/serialization/utils.py

Removes accidentally left in debug printing in python interface

Remove Unnecessary Debug Output

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Compiler/Options.inc
dawn/src/dawn4py/_dawn4py.cpp
gtclang/src/gtclang/Frontend/GTClangASTConsumer.cpp

Since serialize_iir is a boolean also.

Make deserialize_iir a boolean

---

scripts/build-and-test
scripts/daint-test
scripts/daint_test.sh

Move testing script. Requires manual updating in Jenkins.

Move srun_dawn_PR.sh to scripts/daint_test.sh

---

dawn/test/integration-test/unstructured/CMakeLists.txt
gtclang/test/integration-test/CodeGen/CMakeLists.txt
scripts/build-and-test
scripts/daint-test

Use GTEST_OUTPUT instead of loops inside `build-and-test`.

Remove copy-test-xml in favor of env variable

---

scripts/daint-test

Put gtest output in subdirectory

---

dawn/src/dawn/Compiler/DawnCompiler.cpp
dawn/src/dawn/Optimizer/OptimizerOptions.h
dawn/src/dawn/Optimizer/PassOptions.inc
dawn/src/dawn/dawn-opt.cpp
gtclang/src/gtclang/Frontend/GTClangASTConsumer.cpp

Extract the multistage merger and make it a separate group

Multistage Merger as separate Group

---

dawn/src/dawn/Support/Exception.cpp
dawn/src/dawn/Support/Exception.h

Fixes issue with unsigned in exceptions and adds a few more.

Fixup and expand exceptions

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp

Fix latest docker build issue by correcting header filename.

Fix Docker build

---

dawn/src/dawn4py/serialization/utils.py

Import Iterable from collections.abc

---

dawn/setup.py

Fix python3 executable detection in CMake

---

dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp
dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.h
dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.h
dawn/test/integration-test/dawn4py-tests/data/ICON_laplacian_stencil_ref.cpp

This PR addresses a few problems in the code generation for vertical index fields uncovered using the e2e repository.
Testing in e2e repo

Some Cuda Ico Fixes to Make Vertical Indirection E2E Tests Working

---

dawn/src/dawn/Support/Logger.cpp

As the title says
resolves #1044

Switch warnings to stderr

---

dawn/src/dawn/CodeGen/CXXNaive-ico/CXXNaiveCodeGen.cpp
dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp
dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
dawn/src/dawn/CodeGen/Cuda-ico/LocToStringUtils.cpp
dawn/src/dawn/CodeGen/Cuda-ico/LocToStringUtils.h
dawn/src/driver-includes/to_vtk.cpp
dawn/src/driver-includes/unstructured_domain.hpp

A few bug fixes related to subdomains:
* correct an off by one in horizontal size
* fixes number of threads vs stride confusion
Furthermore:
Small improvement in the vtk serialization code
Contains this [enum hack](https://github.com/MeteoSwiss-APN/dawn/pull/1108), tbd
Can only be tested in integration

Some Fixes in cuda Codegen regarding Subdomains

---

dawn/src/dawn/Validator/UnstructuredDimensionChecker.cpp
dawn/test/integration-test/dawn4py-tests/vertical_indirection.py
dawn/test/unit-test/dawn/Validator/TestUnstructuredDimensionChecker.cpp

During the integration workshop it was noted that there seems to be a problem with dawn when using sparse index fields. Further investigation revealed that, while sparse index fields are fully supported, this was rather a case of too strict dimensions checking. It was required that `a[b] <=> dim(a) == dim(b)`, which is too strict if the index fields are used in reductions. This PR basically relaxes the dimensions checking for index fields to the same rules as for normal fields in reductions, while leaving the `a[b] <=> dim(a) == dim(b)` for point-wise situations. 
Fixes #1106 
We basically want to enable stencils like the following, which is a stripped down version [of a real ICON stencil](https://github.com/dawn-ico/ICON-DSL/pull/21). 
```
@stencil
def a_stencil(
a: Field[Cell, K],
b: …
```

Fix a Bug in the Unstr. Dim Checker w.r.t. Index Fields

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
dawn/src/driver-includes/bindings/dawn_utils.f90
dawn/src/driver-includes/cuda_utils.cpp
dawn/src/driver-includes/cuda_utils.hpp
dawn/src/driver-includes/to_vtk.cpp
dawn/src/driver-includes/to_vtk.h

Tested in ICON-DSL https://github.com/dawn-ico/ICON-DSL/pull/24
resolves #1112

Serialize to csv and fix set_splitter_index

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
dawn/src/dawn/CodeGen/F90Util.h
dawn/src/driver-includes/cuda_verify.hpp
dawn/test/integration-test/unstructured/GenerateUnstructuredStencils.cpp

Also contains a magic number fix in unstructured tests that was making them fail.
Testing on ICON-DSL.

Add optional tolerance and fix relative error computation

---

dawn/src/driver-includes/cuda_verify.hpp

Rolling back to the old way of measuring the relative until we get a better understanding

Roll Back Error Measure

---

dawn/src/dawn/CodeGen/Cuda/CudaCodeGen.cpp
dawn/test/integration-test/dawn4py-tests/data/copy_stencil_ref.cpp
dawn/test/integration-test/dawn4py-tests/data/hori_diff_stencil_ref.cpp
dawn/test/integration-test/dawn4py-tests/data/tridiagonal_solve_stencil_ref.cpp
dawn/test/unit-test/dawn/CodeGen/reference/conditional_stencil.cu
dawn/test/unit-test/dawn/CodeGen/reference/global_indexing.cu
dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil.cu
dawn/test/unit-test/dawn/CodeGen/reference/laplacian_stencil_nosync.cu
dawn/test/unit-test/dawn/CodeGen/reference/nonoverlapping_stencil.cu
dawn/test/unit-test/dawn/CodeGen/reference/update_dz_c.cu

Patch structured cuda backend to have same indexing of fields of naive.

Apply cuda codegen patch (from Joerg Behrens)

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp

Fixed positional function argument bug in Fortran wrapper codegen

---

scripts/daint-test

The account `c14` was disabled by cscs. This PR changes the account accordingly.

Change Account on daint from c14 to g110

---

.github/workflows/nightly-merge.yaml

This PR adds a github action that merges the changes to `master` automatically into the `offsetReduction` branch provided to Joerg Behrens from the DKRZ. It triggers each time the `master` branch is updated.

GitHub Action to keep offsetReduction branch up to date

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp

The guards in the `cuda-ico` codegen guarding against stencils with empty domains caused problems; they were formulated like so:
```
if (hsizeXXX == 0) {
return;
}
```
causing subsequent stencils to not be run if `hsizeXXX` was indeed zero. This PR addresses this by conceptually inverting the guard, i.e. only running the stencil if `hsizeXXX == 0`
Tested using `icon-cscs`

Fix Check Guarding Against Empty Region in Codegen

---

dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp
dawn/src/driver-includes/bindings/dawn_utils.f90
dawn/src/driver-includes/cuda_utils.cpp
dawn/src/driver-includes/cuda_utils.hpp

The subdomain mechanism is reworked to be consistent with the c++ and python conventions, see [here](https://jenkins-mch.cscs.ch:8081/job/icon-dsl-PR/) for a more detailed explanation. The consequence of this endeavor for dawn is that the `set_splitter_index_upper` and `set_splitter_index_lower` functions are replaced with a single `set_splitter_index` function.

Rework Subdomains
